### ISSUE TITLE
Issue with new lines indentation

### ISSUE THREAD

**Issue by gigo6000** [AstroNvim/AstroNvim#1008]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v1.9.2-3-g70eca78e321c

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

MacOS 12.5

### Describe the bug

I'm having issues with indentation, when I create a new line, hitting Enter or typing "o" the cursor is indented based on the outer most tag, and not on the current tag, as shown in the video. I recently switched from Vim to Neovim so not sure if I'm missing something.

https://user-images.githubusercontent.com/387648/192499421-9c0ebfbe-785a-4734-a6cf-81f9d4a4e6ce.mp4

### Steps to Reproduce

1. Go to any tag with multiple children tags in jsx, html or php
2. Position the cursor in the deepest children
3.  Type "o" in insert mode
4.  The cursor is indented to the outer most  (parent) tag

### Expected behavior

When a new line is created the cursor should be indented based on the current tag (where the cursor is)

**Comment by mehalter** [comment]
This is probably a limitation of the regex based indentation in neovim/vim. You could try enabling treesitter based indentation to see if that performs better. Treesitter's indent support is still "experimental" and we have seen some issues with it in particular with Python, but I haven't seen much issues in other places. Here is a minimal `user/init.lua` file that just enables treessitter indentation:

```lua
return {
  plugins = {
    treesitter =  {
      indent = { enable = true }
    }
  }
}
```

Could you see if that resolves the problem you are running into? 

Also just for some context, AstroNvim doesn't do anything specific for configuring contextual indentation since these are built in features for Neovim, so there isn't really a bug on our end to fix. Hopefully the treesitter indentation resolves it though :D

**Comment by gigo6000** [comment]
Interesting I thought Neovim would handle this better by default. I actually had this working fine on my previous `.vimrc`  I think all I had was:
```vim
set autoindent                 " Copy indent to the new line
```
I tried that, but it didn't work, not sure if I put it in the wrong please?:
```lua
  -- Configure plugins
  plugins = {
   init = {
   ... 
   treesitter = { -- overrides `require("treesitter").setup(...)`
      ensure_installed = { "lua" },
      indent = { enable = true },
    },
```

Sorry for posting this issue here, I just switched from VIM to Neovim, I've being using VIM for over a decade I think but I feel like a total noob with Neovim.  And thanks for AstroNvim, you've done a great work,  I just needed to tweak a few things and I'm still working on it, but most of the default config is what anyone needs to start coding.

I guess I would need to keep learning more about Neovim indentation. Thanks

**Comment by mehalter** [comment]
If you had good results with `autoindent` in the past you could try setting that in your lua config as well and see if that works out, I think that should look something like this:

```lua
return {
  options = {
    opt = {
      autoindent = true,
    },
  },
}
```

Also I believe you have put that in the correct place for the treesitter stuff, main thing is to make sure you have closed the `init` table

```lua
  -- Configure plugins
  plugins = {
   init = {
   ... 
   }, -- <-- HERE YOU NEED TO MAKE SURE THE plugins.init TABLE IS CLOSED
   treesitter = { -- overrides `require("treesitter").setup(...)`
      ensure_installed = { "lua" },
      indent = { enable = true },
    },
```

**Comment by mehalter** [comment]
@gigo6000 I noticed you have a super cool YouTube channel! Any plans on making anything about AstroNvim 👀 I know there have been a lot of requests about someone making a video on configuration basics in AstroNvim 😂 no pressure in any way, just asking out of curiosity :)

**Comment by mehalter** [comment]
Yeah no worries! That is very exciting! Would love to link to the video on the README and the documentation site if you end up making one. Also just a heads up there is going to be the release of AstroNvim 2.0 along side the release of Neovim 0.8 this upcoming Friday. Neovim 0.8 is going to be released stable and AstroNvim 2.0 will be released in `nightly` September 30, 2022 and then hopefully (🤞🏼) AstroNvim 2.0 will be made stable a week later on October 7, 2022. This will come with some pretty hefty breaking changes. Leading up to the release I am planning on making a pretty extensive migration guide to help guide users through the update and all the breaking changes. Breaking changes can be super annoying which is why we have opted to follow semantic versioning schemes to help make these things predictable and manageable... Hopefully it works out alright haha

**Comment by gigo6000** [comment]
@mehalter here's the video about my switch to AstroNvim: https://youtu.be/71GDopdc9rw hope you like it!

**Comment by mehalter** [comment]
This is awesome! Thanks for sharing! @gigo6000 super great content and I hope you are enjoying AstroNvim so far!

**Comment by gigo6000** [comment]
@mehalter thanks for all the great work on AstroNvim!

**Comment by gigo6000** [comment]
@mehalter let me know if you finally put a link to the video in the README/Documentation, thanks!

**Comment by mehalter** [comment]
Ah yes! I have added it to the README on `nightly` Hopefully it gets merged in after some stuff gets finalized by the end of the week @gigo6000 !

**Comment by gigo6000** [comment]
Awesome! thanks!

**Comment by hholst80** [comment]
@gigo6000 it would be really helpful to have videos on how to customize the plugins.  I have enabled a lot of plugins that are mostly helpful, but sometimes I feel the need to customize them, and really I don't know where and how to do that.  Basic things like custom linter warnings, pretty formatting on save rules etc.  (I am using AstroNvim)

Subscribing in hope of seeing more such content. ;-)
