### ISSUE TITLE
how to use vim.lsp.rpc.connect.

### ISSUE THREAD

**Issue by A-Lamia** [AstroNvim/AstroNvim#1039]
### Question

Just started using nightly everything works fine! Thanks for the hard work.

I was trying to test out the new `rpc.connect` feature with godot not sure if im doing it wrong.

Folder Structure: lsp>server-settings i have the file gdscript.lua.

I also have a servers.lua in lsp folder with
```lua
return {
  "gdscript"
}
```

### User Configuration

What the example is.
```lua
vim.lsp.start({
  name = 'godot',
  cmd = vim.lsp.rpc.connect('127.0.0.1', 6008), -- Port must match your Language server settings within Godot
  root_dir = vim.fs.dirname(vim.fs.find({'project.godot'}, { upward = true })[1]),
})
```

Mine
```lua
return {
  -- cmd = {'ncat', 'localhost', '6008'} -- what i was using before.
  cmd = vim.lsp.rpc.connect("127.0.0.1", 6008),
  root_dir = vim.fs.dirname(vim.fs.find({ "project.godot" }, { upward = true })[1]),
}

```

**Comment by A-Lamia** [comment]
@mehalter yeah it's the final code block, the whole code block even.

**Comment by mehalter** [comment]
Ah I see, it's because this is a `vim.lsp` command and the `lsp` stuff in AstroNvim all goes through `lspconfig` plugin which doesn't support this notation yet. I would say instead of doing this with the `lspconfig` table you should do it in your `polish` function:

Here is an example `user/init.lua` file:

```lua
return {
  polish = function()
    vim.lsp.start {
      name = "godot",
      cmd = vim.lsp.rpc.connect("127.0.0.1", 6008), -- Port must match your Language server settings within Godot
      root_dir = vim.fs.dirname(vim.fs.find({ "project.godot" }, { upward = true })[1]),
    }
  end,
}
```

I noticed you are splitting up your config. You can just put this in `user/polish.lua`:

```lua
return function()
  vim.lsp.start {
    name = "godot",
    cmd = vim.lsp.rpc.connect("127.0.0.1", 6008), -- Port must match your Language server settings within Godot
    root_dir = vim.fs.dirname(vim.fs.find({ "project.godot" }, { upward = true })[1]),
  }
end
```

You might want to add some lua logic in place to only start this for a specific filetype. But if you do this I would remove the stuff for `godot` from your `lsp` tables to make sure AstroNvim doesn't try setting it up.

**Comment by A-Lamia** [comment]
@mehalter apparently the changes was already made by lspconfig but I'm unsure what to put in to my lsp settings to get this to actually work.

**Comment by A-Lamia** [comment]
@mehalter So i can get a connection just by adding godot to servers.lua and having no server-settings but nothing works godot says LSP connected but the LspInfo shows no clients attached.
