### ISSUE TITLE
Add an element to quickly change init.lua to the dashboard (as done in  LunarVim) and to the <leader>l menu

### ISSUE THREAD

**Issue by rozhelluk** [AstroNvim/AstroNvim#1074]
### Describe the new feature

Add an element to quickly change init.lua to the dashboard (as done in  LunarVim) and to the <leader>l menu.

### Additional context

This will save a lot of time in setting up the custom configuration.

**Comment by mehalter** [comment]
This is a tricky one for cases where users do not have an `init.lua` file and rely on splitting up their configuration around different files. Maybe it's enough to just put this binding and people that do keep a single config file can use it and others just don't

**Comment by mehalter** [comment]
I started taking a look at this and I think for the general case it's not super easy for our set up. Mainly because there are many ways to set up user configuration files and they are not always present in the same places for everyone. You can have them in `~/.config/nvim/lua/user` or `~/.config/atronvim/lua/user` either using `init.lua` or splitting up the configuration across many files to the point where you could have no `init.lua`. Also out of the box there is no user configuration in the beginning so that binding wouldn't be useful. And it's tricky to tell which one to check for and when. Sorry for this :(
