### ISSUE TITLE
["mehalter/nvim-window-picker"] failed to update.

### ISSUE THREAD

**Issue by x-ray-s** [AstroNvim/AstroNvim#1094]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.2.0

### Neovim version (>= 0.7)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

20.04.3 LTS (Focal Fossa)

### Describe the bug

`mehalter/nvim-window-picker` this repo does not exist, so `PackerSync` will be failed to sync.

### Steps to Reproduce

1. nvim +PackerSync
2. failed to update

### Expected behavior

Instead of https://github.com/s1n7ax/nvim-window-picker/commits/main and update packer_snapshot

**Comment by mehalter** [comment]
Ah sorry about that @x-ray-s ! I had to rebase my branch because of some changes the dev made to get this PR into the main repo. 

To fix this, please delete and reinstall the plugin with these commands:

```sh
rm -rf ~/.local/share/nvim/site/pack/packer/opt/nvim-window-picker
nvim +PackerSync
```

My PR is finished and hopefully will be merged soon and this shouldn't be a problem anymore. Sorry again!

**Comment by x-ray-s** [comment]
Ok, I fixed it locally, I change the config Lua and packer_snapshot. Your reply is timely. Thanks for your work.

**Comment by mehalter** [comment]
oh yeah dang, I will need to fix that, sorry :( I forgot about the packer_snapshot :/

**Comment by mehalter** [comment]
I will tag a new patch release now :)
