### ISSUE TITLE
LSP Format sends a failure notification everytime on file save if the LSP is in the disabled list

### ISSUE THREAD

**Issue by shans10** [AstroNvim/AstroNvim#1112]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.2.2

### Neovim version (>= 0.7)

NVIM v0.8.0

### Operating system/version

Arch Linux

### Describe the bug

 If `format_on_save` is set to `true` and I add an LSP in the disabled list and there is no other provider enabled in the workspace for formatting the file then everytime I save the file a notification appears with the following message:
**[LSP] Format request failed, no matching language servers.**

### Steps to Reproduce

1. Make sure sumneko_lua is the only lsp enabled for lua files

2. Add the following to the user/init.lua file:

```
    -- Extend LSP configuration
    lsp = {
        formatting = {
            format_on_save = true, -- enable or disable auto formatting on save
            disabled = { -- disable formatting capabilities for the listed clients
                "sumneko_lua",
            },
            -- filter = function(client) -- fully override the default formatting function
            --   return true
            -- end
        },
    },
```
3. Now whenever any .lua file is saved it will display the above notification.

### Expected behavior

If all LSPs/null_ls providers that provide file format capabilities are disabled then it should automatically disable format_on_save if there is no provider available.

### Screenshots

![Screenshot from 2022-10-15 13-10-19](https://user-images.githubusercontent.com/28944997/195975417-494e0e37-ef08-4119-9e6d-fad9f41681a9.png)

**Comment by mehalter** [comment]
Hm I'm not sure if there's a good way to detect this automatically during runtime in this way. I do think there is a new feature currently in AstroNvim nightly that should be released next week that allows you to have more control over formatting on save. This includes disabling the auto formatting for filetypes. In your case you could disable format on save for `lua` files and then this notification wouldn't show up. This would also let you leave sumneko Lua enabled for formatting and then you could use the format binding on demand if you ever wanted to.

I also checked the docs to see if there would be a way to disable this notification and I don't think that's currently a feature :/ sorry I can't solve this directly because of limitations in the Neovim API, but I hope the work around I described meets your needs! :)

**Comment by shans10** [comment]
> In your case you could disable format on save for lua files and then this notification wouldn't show up. This would also let you leave sumneko Lua enabled for formatting and then you could use the format binding on demand if you ever wanted to.

Thank you this workaround is perfect and exactly what I need :)
