### ISSUE TITLE
Possible to override user/init.lua?

### ISSUE THREAD

**Issue by dohsimpson** [AstroNvim/AstroNvim#1134]
### Question

First of all, I'm a big fan of the project. Haven't been this excited about something like this for years. Seeing how frequent you make commits is absolutely impressive.

I have a use case where I want to share the astronvim config between my personal and work station. The majority of the config should stay the same, but I want to add some work station specific customization.

For example,

If I want to use a different configuration for a custom plugin only for the workstation. Currently, I would have to add conditionals in that plugin configuration in usre/init.lua.

The problem is, that is fine if it doesn't occur often, but when it occurs often, it makes the config less maintainable and readable.

Question: is there a way to source a separate lua file that can be of the **same structure** as user/init.lua? By same structure I mean it only returns a `config` table. This way, I only need to make minor tweaks/override in that file. In other words, is there a way to merge additional config table in addition to the config table definition in user/init.lua.

**Comment by mehalter** [comment]
You could do this in a variety of ways. One really simple way could be like this:

```lua
local is_windows = vim.fn.has "win32" == 1

-- this could also go in a separate place like `user/windows/mappings.lua` and loaded with `require("user.windows.mappings)`
local windows_mappings = {
  n = {
    ["<leader>W"] = { function() vim.notify "THIS IS WINDOWS" end, desc = "Test Windows Mapping" },
  },
}

-- this could also go in a separate place like `user/linux/mappings.lua` and loaded with `require("user.linux.mappings)`
local nix_mappings = {
  n = {
    ["<leader>L"] = { function() vim.notify "THIS IS LINUX" end, desc = "Test Linux Mapping" },
  },
}

return {
  -- astronvim.default_tbl(opt, default) will use the first argument
  -- to extend a default table of options provided in the 2nd argument
  mappings = astronvim.default_tbl(is_windows and windows_mappings or nix_mappings, {
    -- global options would go here
    n = {
      ["<leader>Z"] = { function() vim.notify "THIS MAPPING IS AVAILABLE FOR ALL" end, desc = "Test Global Mapping" },
    },
  }),
}
```

Where you use the lua programming language to build the final table that you want to return. This would really just take lua knowledge and understanding of the programming language and being careful that you don't introduce bugs into your logic for building the correct table.

Another way you could go about this is to use a dotfile manager like [chezmoi](https://www.chezmoi.io/) for example to manage different dotfiles between different machines. That way you can configure in whatever dotfile manager you want to use to put the correct code/configuration information into the user config. There are a lot of tools out there for managing dotfiles especially between different machines that may want different options and it would be better to rely on tools built for that rather than AstroNvim trying to bake in it's own multi-machine type management that would almost certainly be less powerful and extendable.

Hopefully this helps point you in the correct direction!

**Comment by mehalter** [comment]
Also just in case you want to see it, here are the lua docs for the `default_tbl` function: https://astronvim.github.io/AstroNvim/modules/core.utils.html#astronvim.default_tbl

This page has all of the documentation for the internal methods and submodules that are available with the `astronvim` global lua variable that we set
