### ISSUE TITLE
What does (not loaded) means ?

### ISSUE THREAD

**Issue by rokonio** [AstroNvim/AstroNvim#1146]
### Question

When I use `:PackerStatus` I see that after the line for LuaSnip, there's written (not loaded). What does that mean ? Can I use the plugin as usual ?

**Comment by mehalter** [comment]
Yeah, we do a lot of lazy loading of plugins so they are loaded when they are needed rather than loading everything on startup. Once you go into insert mode for the first time in a session it should load stuff like `cmp` and `luasnip` and completion related stuff since before you enter insert mode there is no way to use snippets or completion :)

**Comment by rokonio** [comment]
Thank you for the rapid answer !

I was also wondering what were the names of the different modes available in the key mapping (for example n is normal, but xhat does t mean ?)
