### ISSUE TITLE
Can't to open terminal with ctrl + \

### ISSUE THREAD

**Issue by PratamaRizki22** [AstroNvim/AstroNvim#1152]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.4

### Neovim version (>= 0.8)

v0.8.0-1210-gd367ed9b2

### Operating system/version

Wsl ubuntu

### Describe the bug

Cant to open terminal in astrovim

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/96802430/197239934-b8a85e6f-fb09-4127-aa81-bcb7ae281bdd.png)

### Expected behavior

can to open terminal

### Screenshots

![image](https://user-images.githubusercontent.com/96802430/197239973-533e124f-9230-44b3-ac45-4459fb84f0a8.png)

**Comment by mehalter** [comment]
This binding has been changed to `F7` since `v2` as specified in the Migration Guide. This binding conflicted with some very very important default bindings for controlling terminal mode: https://astronvim.github.io/Configuration/v2_migration

You can check the default mappings here: https://astronvim.github.io/Basic%20Usage/mappings#toggle-terminal-mappings
