### ISSUE TITLE
:bd crashes nvim

### ISSUE THREAD

**Issue by TheButlah** [AstroNvim/AstroNvim#1165]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.4.2

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 12.6

### Describe the bug

`:bd` crashes `nvim`

### Steps to Reproduce

1. Run `nvim`
2. Open the file tree: `<SPACE>e`
3. Edit a file: `:e foo.txt`
4. Edit another file: `:e bar.txt`
5. Close the current buffer: `:bd`

### Expected behavior

`:bd` should merely close the current buffer, not exit nvim completely

### Screenshots

https://user-images.githubusercontent.com/6969415/197542344-e0e53ac2-386e-4ec8-889e-b60eaa7ebf07.mov

### Additional Context

Return code:
```
❯ echo $?
0
```

**Comment by cseickel** [comment]
This is something that is really a misunderstanding or difference of opinion on what `close_if_last_window` means. See these closed issues for reference:

https://github.com/nvim-neo-tree/neo-tree.nvim/issues/241

https://github.com/nvim-neo-tree/neo-tree.nvim/issues/364

The relevant suggestions from those are:

> It sounds to me that what you actually want is to have nvim switch to the most recently used buffer when you delete the one that is active in a window, instead of closing the window. If that's correct, there is a plugin for that: https://github.com/famiu/bufdelete.nvim

or disable `close_if_last_window` and use this instead:

```
augroup CLOSE_IF_LAST_BUFFER
    autocmd!
    autocmd BufDelete * silent! if len(getbufinfo({'buflisted':1})) == 0 | q | endif
augroup END
```

**Comment by TheButlah** [comment]
Does this mean this issue should be reopened? Is this a bug or expected behavior - I'm confused

**Comment by cseickel** [comment]
@TheButlah it is expected behavior. The confusion comes from the difference between neovim's concept of buffers and windows vs how other than editors represent them. Because astrobim chooses to represent buffers as tabs, it creates some breaks in the mental model vs reality.

The short answer is you should not use 'bd', you should use whatever command is appropriate for this config to close what you are thinking about as a tab.

**Comment by mehalter** [comment]
@TheButlah The recommendation here is that a good approach for the task you are trying to do is to use the plugin: https://github.com/famiu/bufdelete.nvim

This is actually bundled with AstroNvim which we have mapped out of the box to `<leader>c`. Could you try using this binding to see if this does what you are expecting it to rather than `:bd`.
