### ISSUE TITLE
Is there any Animation Cursor option?

### ISSUE THREAD

**Issue by AlphaVCat** [AstroNvim/AstroNvim#1208]
### Question

Can we use any Animation Cursor like this [NeoVideVIm](https://github.com/neovide/neovide)?
Or i'm download this VideVim with AstroNvim conf and it's work perfectly, but if i want to change some option in VideVim we need a `init.vim` file in the Nvim config dir `~/.config/nvim/init.vim`, how can we create this file with in the same dir of init.lua?

**Comment by marchellodev** [comment]
@AlphaVCat Neovide is a gui for vim. It is not a terminal (where vim is usually used), but a separate application which consumes vim draw commands and draws gui based on them. As a result, neovide can do some cool animations and transitions. It is impossible to get all those animations in a regular terminal.

You can configure neovide in `~/.config/nvim/lua/user/init.lua`. There is a lot of info available on the astrovim's website about how to configure astrovim: https://astronvim.github.io/Configuration/manage_user_config. However, astrovim prefers to use lua instead of vimscipt

On the neovide website, they provide an example of how to configure it with vimscript. However, everything that can be done in vimscript can also be done in lua. Here's an example of how to configure some things in lua:

https://github.com/neovide/neovide/issues/1211

**Comment by AlphaVCat** [comment]
Thanks! It's worked.

![neovide](https://user-images.githubusercontent.com/114478214/198933588-18cc1dd2-a1c1-49a7-b409-7523a2dc0509.jpg)
