### ISSUE TITLE
Opening neo-tree on dashboard causes it to be stuck in root folder

### ISSUE THREAD

**Issue by jayp0521** [AstroNvim/AstroNvim#1214]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.5.0

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

arch latest

### Describe the bug

https://asciinema.org/a/MtlwTUpnQPoCJZYOPkC18vSQC

### Steps to Reproduce

1. open neovim
2. open neotree
3. close neotree
4. open file from telescope
5. open neotree
6. neotree stuck on root dir

`neo-tree.lua`

```
return {
	close_if_last_window = true,
	filesystem = {
		filtered_items = {
			hide_dotfiles = false,
			hide_gitignored = false,
		},
	},
	sort_case_insensitive = true,
	group_empty_dirs = true,
	renderers = {
		directory = {
			{ "indent" },
			{ "icon" },
			{ "current_filter" },
			{ "name" },
			{ "clipboard" },
			{ "diagnostics", errors_only = true },
		},
		file = {
			{ "indent" },
			{ "icon" },
			{
				"name",
				use_git_status_colors = true,
				zindex = 10,
			},
			{ "clipboard" },
			{ "bufnr" },
			{ "modified" },
			{ "diagnostics" },
			{ "git_status" },
		},
	},
	window = {
		position = "float",
		width = "100%",
	},
}
```

### Expected behavior

Tree always follows the file

### Screenshots

[![asciicast](https://asciinema.org/a/MtlwTUpnQPoCJZYOPkC18vSQC.svg)](https://asciinema.org/a/MtlwTUpnQPoCJZYOPkC18vSQC)

**Comment by mehalter** [comment]
This is unrelated to the Dashboard. This  happens even if the Dashboard is disabled and you just do this on a blank buffer. I believe this is happening because Neo-tree shows things relative to your current working directory and doesn't change the current working directory. If you jump to a file that is extremely nested then this will become relatively not useful. There may be a nesting maximum. You could modify your setup to automatically change the working directory when you change files. Or a binding to change your working directory to the current file's folder. Other than that I don't have much guidance. You might want to ask on the `neo-tree` repo to see if they consider this a bug or if they have any recommendations. On the AstroNvim side we aren't doing anything to configure this on top of what the default behavior is for Neo-tree.

Sorry this isn't the most helpful answer, but hopefully points you in the right direction :)

**Comment by jayp0521** [comment]
sure, just wanted confirmation that it is not from astronvim. note: after I open a file then open `neo-tree` for the first time. everything works as intended
