### ISSUE TITLE
Why is this line not being changed by my theme? Tried many themes and none of them work.

### ISSUE THREAD

**Issue by IcyKit** [AstroNvim/AstroNvim#1237]
### Question

![Снимок экрана 2022-11-03 в 16 52 56](https://user-images.githubusercontent.com/84917134/199740419-30f04c2d-f916-496c-9983-d0bfcddac543.png)

**Comment by mehalter** [comment]
Could you please link the theme that you are trying and I can take a look at them? We are using the `Winbar` highlight group for setting those colors

**Comment by IcyKit** [comment]
> Could you please link the theme that you are trying and I can take a look at them? We are using the `Winbar` highlight group for setting those colors

I've tried to use gruvbox, everforest, nord and catppuccin themes.

**Comment by IcyKit** [comment]
My bad, u asked links.
[gruvbox](https://github.com/morhetz/gruvbox)
[nord](https://github.com/shaunsingh/nord.nvim)
[everforest](https://github.com/sainnhe/everforest)
[catppuccin](https://github.com/catppuccin/nvim)

**Comment by mehalter** [comment]
Ah, I see there was a shortcoming in the utility function for me resolving the highlight groups! Thanks for catching this! Could you please check out the latest `nightly` and see if it resolves your issue? :) I have tested each of the colorschemes that you sent as well as a few others and I think it should be working much better.

What was happening is we are using a utility function to get the `fg` and `bg` color of each highlight group, but it's not handling when a highlight group only defines `fg` and not `bg` so it was falling back to the `default_theme` default for this rather than resolving to the `Normal` bg for the given theme.

**Comment by mehalter** [comment]
To easily test our the `nightly` channel just update the `updater` table in your `user/init.lua` file to have this:

```lua
  updater = {
    channel = "nightly",
  },
```

And then run a `:AstroUpdate` :)

**Comment by IcyKit** [comment]
It seems like my astro does not see updates.
![Снимок экрана 2022-11-03 в 18 12 03](https://user-images.githubusercontent.com/84917134/199759522-c3e531a1-5864-4809-8975-ece24cba781d.png)
![Снимок экрана 2022-11-03 в 18 12 32](https://user-images.githubusercontent.com/84917134/199759631-76305a39-123d-4ab2-a731-d9ca33b019e4.png)

**Comment by mehalter** [comment]
ah, you will want to remove the `branch = 'main'`. This will make you follow the `nightly` rules but check out the `main` branch. Could you just delete the `branch` line and it will figure out what branch to do automatically

**Comment by IcyKit** [comment]
Whoa, it's working now! Thanks!

**Comment by IcyKit** [comment]
You are doing a great job for the happiness of the developers!

**Comment by mehalter** [comment]
Yay, thank you for the kind words! I will release this patch now :)
