### ISSUE TITLE
tabnine integration

### ISSUE THREAD

**Issue by mozrelic** [AstroNvim/AstroNvim#1255]
### Question

I'm a nvim and lua noob, please forgive me if this is a stupid question:

I'm trying to integrate tabnine (https://github.com/tzachar/cmp-tabnine), and I found the "Customize cmp Completion" documentation (https://astronvim.github.io/Recipes/cmp) for AstroNvim. Following the directions I found here, I modified my `user/init.lua` `plugins.init` thusly:

```lua
plugins = {
  init = {
            ["tzachar/cmp-tabnine"] = {
                after = "nvim-cmp",
                run = "./install.sh",
                config = function()
                    astronvim.add_user_cmp_source "cmp_tabnine"
                end,
            },
  },
}
```

and also added `cmp_tabnine = 1000,` to `cmp.source_priority`. 

Autocomplete provided by tabnine seems to work when I run nvim from inside my `users` dir, but it will not work, and `:CmpStatus` shows tabnine as unused when I run nvim from outside of the `user` dir

my `init.lua` file is otherwise exactly the same as the `user_example.lua` file provided by AstroNvim.

What am I doing wrong?

Thanks.

**Comment by mehalter** [comment]
I'm not sure why it would show as unused in `:CmpStatus`. I also don't use tabnine so I won't be able to try it out and give feedback. This is a good question for the discord since other users use this successfully. I will say that the code you sent does appear to work since it shows tabnine in `:CmpStatus` so you know it's loading the plugin and connecting it to `cmp`. Outside of that I don't know how to configure that plugin in particular.
