### ISSUE TITLE
disable formatting at save for lua-files

### ISSUE THREAD

**Issue by kraxli** [AstroNvim/AstroNvim#1259]
### Question

I use @mehalter super nice configuration with a few adjustments. Adding e.g. a plugin to the `plugins/init.lua` and saving the file formats the whole file "destroying" the git-history. Following the informative [AstroNvim documentation](https://astronvim.github.io/Recipes/advanced_lsp#customizing-auto-format-on-save), I have enhanced my `user/init.lua` file with

```lua
return {
	lsp = {
		formatting = {
			format_on_save = {
				-- enabled = false, -- enable format on save
				ignore_filetypes = { -- disable format on save for specified filetypes
					"lua",
				},
			}
		},
	},
}
```

At first this had no effect after restarting. However after running `AstroReload`, `lua`- files are not formatted anymore. But now at each `save`, I get the notification  `INFO [LSP] Format request failed, no matching language servers.`.  Is this intended?

**Infos**:
- neovim version: 0.8
- AstroNvim version: v2.6.1
- most recent pull from @mehalter repo.
- os: Linux Mint 21

### User Configuration

```lua
IS_WINDOWS = (vim.fn.has("win32") == 1 or vim.fn.has("win64") == 1)

pcall(require, "local.settings")

return {
	lsp = {
		formatting = {
			format_on_save = {
				-- enabled = false, -- enable format on save
				ignore_filetypes = { -- disable format on save for specified filetypes
					"lua",
				},
			},
		},
	},
}
```

**Comment by mehalter** [comment]
If you are using my config, you will notice that I have the file `user/lsp/formatting.lua`. You will need to put these settings in that file. As described in the documentation regarding splitting up the config, separate files take precedence over `user/init.lua`. so that file will not be used to load that option since other formatting options are defined in a separate file.

Also as a note, I wouldn't particularly recommend using my config. There are a lot of things that are pretty specific to my computer, personal scripts, and my workflow that almost certainly won't apply to anyone else
