### ISSUE TITLE
Overriding default keybindings

### ISSUE THREAD

**Issue by FadeevNikolay1999** [AstroNvim/AstroNvim#1260]
### Question

Hello, First of all thank you for this amazing distro. I have two questions: 
1. I wanted to override some keys and everything works perfect except one thing. I cannot override default mapping "gl" that stands for "Hover diagnostic". Could you please tell me how to do it?

2. how to use "cmd" key when mapping? <cmd-[key]> : ... ? <D-[key]> : ... ?  

<img width="1440" alt="Screenshot 2022-11-06 at 18 07 26" src="https://user-images.githubusercontent.com/79904092/200178845-4889583c-b30f-4ddc-a27e-297a2d5b306e.png">

<img width="1440" alt="Screenshot 2022-11-06 at 16 43 56" src="https://user-images.githubusercontent.com/79904092/200174548-f2b083b0-32cf-4452-8c0b-45212095d77c.png">

**Comment by mehalter** [comment]
`gl` is part of the LSP mappings. It is set in a different table, `lsp.mappings` because we don't want to attach that mapping unless a language server is attached. The main thing you want to do is to just disable that mapping in the `lsp.mappings` table so it never gets set, and then keep the mappings that you are defining as they are.

You just need to add the following to your `lsp.mappings` table (this is a complete `user/init.lua` example):

```lua
return {
  lsp = {
    mappings = {
      n = {
        gl = false,
      },
    },
  },
}
```

As for mapping the Cmd key, this is the same as the "Windows" key and is typicaly referred to as the "Super key". This can be a bit tricky to map, I would say to start by googling how to map the super key in vim. Here is a link that came up: https://stackoverflow.com/questions/327415/can-windows-key-be-mapped-in-vim

Hopefully this can point you in the right direction!
