### ISSUE TITLE
whic nvim framework should i select

### ISSUE THREAD

**Issue by alavaelian** [AstroNvim/AstroNvim#1273]
### Question

i wanna know what is the better nvim config lunar vim or astro vim i apologize if it someting that i cant ask here

**Comment by mehalter** [comment]
Thanks for asking this and contributing to the community discussion. Hopefully some other community members can chime in with their opinions as well. At the end of the day it definitely all comes down to preference. I will say that as one of the main developers I definitely have bias in these opinions especially regarding the configuration mechanisms in AstroNvim vs other Neovim configurations (since that's my main contribution here).

AstroNvim is much younger than LunarVim and with that comes with less development and potentially less stability and testing in the community.

My own personal reasons to join AstroNvim and helping guide it's development lies in two main points. (1) AstroNvim's code base has minimal abstraction and is organized similar to how any one would make their own configuration with some helper functions to help provide configuration entry points. This allows users to easily browse the internal code base and understand how it works. This is useful for both understanding how to set up and configure their own set ups as well as keeps the code base clean enough that people in the community can still contribute code. (2) The configuration engine in AstroNvim is extremely powerful and takes the stance of "While we are an opinionated Neovim pre-configuration, we cannot expect all people to agree with those opinions and they should be able to override every single aspect of the code that we put forth out of the box. In my opinion this configuration mechanism is unmatched compared to other Neovim configurations. It does require some level of Lua and how to configure Neovim already, or some time to sit down and learn that type of stuff. But we set up our user configuration to reflect the Lua APIs that are are configuring.

On top of these points, I will also say that compared to LunarVim, AstroNvim does have a much much faster start up time and performance. Although I do have to say that NvChad has faster start up time than AstroNvim currently. Between NvChad and AstroNvim they are quite similar and are both under a noticeable threshold. The startup time for LunarVim (at least in my opinion) is quite noticeable.

What it comes down to in the end is the idea that each of these pre-configurations each are "opinionated" and will enforce those "opinions" unless you do some level of user configurations to change some of them. So I think a good way to pick one is to see what opinions each one enforces and pick the one with the least amount of opinions you disagree with. This will lead to less user configuration on your side and less growing pains.

I hope this provides some good insight into the differences and why I have chosen AstroNvim and have decided to become a co-owner and maintainer. I think it has grown a lot in the past 10 months that it has existed and has made huge leaps in stability, usability, and configurability. Hopefully as the community grows and more people contribute and share feedback this trend can continue!

**Comment by alavaelian** [comment]
thanks for the answer homie
