### ISSUE TITLE
Add new entries to alpha

### ISSUE THREAD

**Issue by trankchung** [AstroNvim/AstroNvim#1309]
### Question

Is it possible to add more entries into alpha dashboard? I tried to add it but it's not working. I tried creating the file `plugins/alpha.lua` but it throws error so I tried creating the `plugsin/alpha/layout.lua` that didn't throw error but the new entry I added didn't show up. I even reloaded the config and re-synced packer and restart nvim too but still no dice.

**Comment by jayp0521** [comment]
per the code, https://github.com/AstroNvim/AstroNvim/blob/main/lua/configs/alpha.lua#L1

`user_plugin_opts("plugins.alpha"` means you need a file at `user/plugins/alpha.lua`. return a table of whatever you want and it will do a https://neovim.io/doc/user/lua.html#vim.tbl_deep_extend() on it

**Comment by trankchung** [comment]
@jayp0521 I did what you suggested and it's working but it's not merging the settings. I defined the code below in `plugsin/alpha.lua` but that's the only thing showed up. The rest of the AstroNvim's settings are gone.

```yaml
return {
  layout = {
    { type = "group",
      val = {
        astronvim.alpha_button("LDR P", "  Projects  "),
      },
    },
  },
}
```

**Comment by mehalter** [comment]
@trankchung I'll be able to send you the correct snippet tomorrow morning

**Comment by trankchung** [comment]
@mehalter Thanks. No rush.

**Comment by mehalter** [comment]
@trankchung basically `vim.tbl_deep_extend` does not play nicely with list based tables because of a bunch of compiler and parsing reasons. For this we provide the `function` override notation described here in the docs: https://astronvim.github.io/Configuration/override_formats#override-function

This lets you fully manipulate the configuration table directly for something like this. The buttons are in the 4th element in the `layout` list. You can basically use `table.insert` function in lua to add the button to the appropriate location in the list of buttons. For example, if you wanted to put the button as the 5th button in the list you could do something like this in `user/plugins/alpha.lua`:

```lua
return function(config)
  table.insert(config.layout[4].val, 5, astronvim.alpha_button("LDR P  ", "   Projects  "))

  return config
end
```

and the result would look like this

![2022-11-14_22:10:52_screenshot](https://user-images.githubusercontent.com/1591837/201817580-c543b6be-209d-4070-a534-0616e8019942.png)

**Comment by mehalter** [comment]
To do this type of manipulation you definitely will need to look at the default table that we use for alpha (https://github.com/AstroNvim/AstroNvim/blob/main/lua/configs/alpha.lua) and see which element in the table you need to modify. Like figuring out that the buttons are in the 4th item in the `layout` list and then that the list of buttons are in the `val` property. You could also use this method to remove buttons or do anything else. You could also always just not use the input `config` table and just return a brand new table ignoring what we set all together.

**Comment by mehalter** [comment]
Also if you just wanted to add it to the end of the buttons that we already define, you can just omit the 2nd argument for position like this:

```lua
return function(config)
  table.insert(config.layout[4].val, astronvim.alpha_button("LDR P  ", "   Projects  "))

  return config
end
```
