### ISSUE TITLE
nvim-neo-tree high levels of lag

### ISSUE THREAD

**Issue by A-Lamia** [AstroNvim/AstroNvim#1345]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.7.4-4gf963772

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

Windows 10

### Describe the bug

nvim-neo-tree is causing very high levels of lag, it used to be slightly laggy but now it is pretty bad.

### Steps to Reproduce

1. use neo-tree

### Expected behavior

No lag

### Screenshots

[](https://user-images.githubusercontent.com/6450181/202595011-40e9c5b0-93ff-4515-a010-cc14c9147514.mp4)

**Comment by A-Lamia** [comment]
This might be because of Git Projects with a git repo up to date (no modified files) and projects with out any git are fast.

**Comment by mehalter** [comment]
@A-Lamia this would be a good issue to open with  `neo-tree` to see if they can provide any insight. I wonder if this is related to windows in any way. I don't get any lag from my end on large git repos with lots of changes on Linux at least.

Also see that this issue is open, not sure if it's related: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/609

**Comment by A-Lamia** [comment]
I'll make a bug report i guess, just disabled it never really used it anyway so not missing out on anything.

**Comment by mehalter** [comment]
Awesome, could you also share the relevant issue you open on `neo-tree` here to follow the discussion? I'll go ahead and close this for now and depending on how the `neo-tree` discussion goes we can reopen it if it comes back to us 😄
