### ISSUE TITLE
Azure Bicep configuration not working/disappearing

### ISSUE THREAD

**Issue by mathwro** [AstroNvim/AstroNvim#1377]
### Question

Hi.

I've just started to try out AstroVim so i'm not completely familiar with the structure just yet.
However i'm trying to configure the LSP for Azure's bicep language, which seems to require some additional custom configuration.

If i use LspInstall Bicep, the lsp will be installed and used in that current session. However without any colorization.

As soon as i close the session and start a new i will be told that bicep language server is not in my path.

I don't really know how to approach fixing it, since it's kind of working in the first session.

Any ideas or experience ?

Thanks

**Comment by whoop-t** [comment]
Syntax highlighting(colorization) comes from treesitter (TSInstall Bicep) if treesitter supports it. It doesnt look to be on the [supported lang list](https://github.com/nvim-treesitter/nvim-treesitter#supported-languages)

Is bicep installed on your machine?

I dont use bicep but when I try to LspInstall bicep, i get errors from not having it installed/in my path

**Comment by mathwro** [comment]
Bicep is installed on my machine and are present in my path. "bicep-lsp" is however removed everytime i close my neovim session, which is the confusing part. LspInstall works just fine and allows me to start the lsp for bicep immediately after. But i have to perform the install every time i want to use it

**Comment by whoop-t** [comment]
hmmm im not sure why it would remove itself

You could try adding it to your `user/init.lua` in the plugins object like this:
```
    ["nvim-lsp-installer"] = {
      ensure_installed = { "sumneko_lua" },
    }
```

**Comment by mehalter** [comment]
@mathwro Mason installs `bicep` into it's own environment. So it will not be in your path when you leave Neovim, but it will be present in the path when you open it. If you install `bicep` separately you will want to uninstall it from `mason` because AstroNvim will prefer the `mason` installation over what's installed on your system directly.

Check out this page in the docs for more information on setting up language servers as well as configuring their options: https://astronvim.github.io/Recipes/advanced_lsp#lsp-setup-without-installer

I haven't had personal experience with Bicep, it might be worth going to the Discord and asking people if they have given it a try.
