### ISSUE TITLE
How can I change the configuration for session manager in user/init.lua?

### ISSUE THREAD

**Issue by Rid1-fz-06** [AstroNvim/AstroNvim#1392]
### Question

I want to make session manager to save sessions automatically as in VSCode. I found that ```Shatur/neovim-session-manager``` plugin supports this feature. I want to change it's configuration so that I can achieve this. How can I do this in ```user/init.lua```?

**Comment by mehalter** [comment]
@Rid1-fz-06 sessions are currently saved automatically since this is the default option in `neovim-session-managere`. You can load the previous session with `<leader>Sl`

We do also have some lazy loading on the session manager so that's the reason it isn't loading the sessions on startup. If you want to change this, you can do this in your `user/init.lua` `plugins.init` table to have `neovim-session-manager` load on startup:

```lua
return {
  plugins = {
    init = {
      ["Shatur/neovim-session-manager"] = { event = "VimEnter" },
    },
  },
}
```

Then it will start loading your previous session on startup automatically. You also might want to disable the alpha dashboard starting on startup, either by disabling the plugin completely if you never use the dashboard, or you can just get rid of our alpha autocmds in your `polish` function:

```lua
return {
  plugins = {
    init = {
      ["Shatur/neovim-session-manager"] = { event = "VimEnter" },
    },
  },
  polish = function()
    vim.api.nvim_del_augroup_by_name "alpha_settings"
  end
}
```
