### ISSUE TITLE
How to configure better-scape.nvim mapping

### ISSUE THREAD

**Issue by mishagantz** [AstroNvim/AstroNvim#1409]
### Question

Hello, I wanted to add capital JJ and JK to escape mappings, but it just doesn't work, what am I doing wrong?

Here is part of `better_escape.lua`:
```lua
local M = {}

local api = vim.api

local settings = {
    timeout = vim.o.timeoutlen,
    mapping = { "jk", "jj" },
    clear_empty_lines = false,
    ---@type string|function
    keys = "<Esc>",
}
```

### User Configuration

```lua
    plugins = {
        -- init
        init = {
            ["max397574/better-escape.nvim"] = {
                settings = {
                    mapping = { "JK", "JJ", "jk", "jj" },
                },
            },


}
```

**Comment by mehalter** [comment]
@mishagantz this should be done with the `plugins.better_escape` table to override the `require("better_escape").setup(...)` call.


```lua
return {
  plugins = {
    better_escape = {
      mapping = { "JK", "JJ", "jk", "jj" },
    },
  },
}
```

**Comment by mishagantz** [comment]
@mehalter thank you very much. If I understand correctly, I should use file names from the configs folder? Like mason or ["mason"] and always use brackets with quotes if the file name with dash and can't be used in a variable-like way?

**Comment by mishagantz** [comment]
and I didn't get why I don't have to acces settings table first

**Comment by mehalter** [comment]
Check out the docs for `better_escape`: https://github.com/max397574/better-escape.nvim#%EF%B8%8Fcustomization

Those things are configured with the `require("better_escape").setup(...)` call which is the API that better escape provides which is what we interface with.

The name of the table entry is the string used in the plugin's `require`, basically the name of the lua module you are configuring.

The `[""]` is syntax to guarantee that the key is parsed correctly. Any string is a valid table key in `lua` so these are equivalent:

```lua
{ mason = "hello" }
{ ["mason"] = "hello" }
```

The `[""]` is really only necessary if there are special characters like this:

```lua
{ ["server-settings"] = "hello" }
```

because `{ server-settings = "hello" }` is not valid lua syntax.

**Comment by mehalter** [comment]
Check out the comments in the `user_example/init.lua` file for more details on configuring AstroNvim: https://github.com/AstroNvim/AstroNvim/blob/main/lua/user_example/init.lua#L217-L268
