### ISSUE TITLE
`<F7>` doesn't toggle terminal for python, node etc

### ISSUE THREAD

**Issue by azinsharaf** [AstroNvim/AstroNvim#1413]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.8.4

### Neovim version (>= 0.8)

0.8.1

### Operating system/version

Windows 11

### Describe the bug

`F7` can toggle the floating terminal but cannot toggle the terminal for `python`,  `node`, etc and returns `can't find a terminal to close.` Is there any way to enable it? In `python` page i can type `exit()` to close the terminal but using `F7` would be easier. 

### Steps to Reproduce

1. `space + tp` (default python mapping)
2. `<F7>` doesn't close the terminal

### Expected behavior

`<F7>` closes terminal in python, node, etc.

**Comment by mehalter** [comment]
We have this separated for a variety of different reasons architecturally. So currently this is by design based on how we are creating the terminals and how the toggleterm toggling feature works, currently we have `<F7>` manage it's one set of terminals and the `<leader>t` toggles manage their own terminals. Sorry I can't provide a good solution for you :(
