### ISSUE TITLE
Changing more LSP functions into Telescope

### ISSUE THREAD

**Issue by Ruthenz** [AstroNvim/AstroNvim#1423]
### Describe the new feature

Hey :) 

First of all wanted to say thanks for all the hard work! you really made it much easier for me to keep using Nvim and still be up to date with everything, your working is amazing! 🙏 

I did want to ask what do you think of moving some more features of LSP (like go to definition and get references) into Telescope? I feel like it is easier to use than what is currently available .

This is what I added in my own config under `mappings.nvim` in the telescope section

```
  maps.n["gr"] = { function() require("telescope.builtin").lsp_references() end, desc = "Get references" }
  maps.n["gd"] = { function() require("telescope.builtin").lsp_definitions() end, desc = "Go to definition" }
```

(And of course removed the necessary lines from `lsp.lua`)

**Comment by mehalter** [comment]
@Ruthenz I went ahead and did this on `nightly`. I moved some of the LSP mappings to use telescope if it is available: definitions/implementations/type definitions/references/workspace symbols

It is still being set through `lsp.mappings` just because that will only show mappings when they are available.

We are still going some testing of the current `nightly` that is adding in some basic debugging features. I will go ahead and close this though since this has been implemented and will be made stable soon
