### ISSUE TITLE
dap: make it easy to configure already installed adapters

### ISSUE THREAD

**Issue by maxbrunet** [AstroNvim/AstroNvim#1429]
### Is your feature related to a problem?

DAP in AstroNvim is a great new feature!

I prefer to use my system package manager to install binaries, but `mason-nvim-dap.nvim` has nice presets and I would like to be able to use them with my already installed adapters:

https://github.com/jay-babu/mason-nvim-dap.nvim/tree/main/lua/mason-nvim-dap/mappings

### Describe the new feature

Support a simple list of adapters in the AstroNvim user config (e.g. `dap.adapters`) and use `mason-nvim-dap.automatic_setup` on them.

This would be in the same fashion as `lsp.servers` with `lspconfig`:

https://github.com/AstroNvim/AstroNvim/blob/5a90c6e34679a14ef3c254354e9fc6a243129642/lua/user_example/init.lua#L138-L142

Support for simple configuration overrides may be needed too, but I have not looked into that yet.

### Additional context

For now, I use `polish` to accomplish it:

```lua
return {
  polish = function()
    local dap_adapters = {
      "delve",
    }
    local dapconfig_ok, dapconfig = pcall(require, "mason-nvim-dap.automatic_setup")
    if dapconfig_ok then
      vim.tbl_map(dapconfig, dap_adapters)
    end
  end,
}
```

**Comment by mehalter** [comment]
This probably won't be a good approach because all of the adapter configurations in `mason-nvim-dap` are not going to work perfectly since some of them do rely on file paths within Mason. I've thought about this a lot and I don't think there is a good way to do this in a general manner. We do currently have `dap.adapters` and `dap.configurations` tables to define your own adapters and configurations for adapters that are installed manually. There are a number of ways that these configurations won't be compatible so it will get messy pretty quickly. I will definitely keep thinking of ways to make this integration better, but for now this isn't super planned with the current architecture of `nvim-dap`. Sorry :(
