### ISSUE TITLE
User Heirline for tabline by default

### ISSUE THREAD

**Issue by mehalter** [AstroNvim/AstroNvim#1464]
We would like to reduce our reliance on redundant plugins. We have an optional Heirline based bufferline currently available, we should replace the Bufferline plugin by default and just use Heirline. This gives us a lot more control over things such as colors and information displayed and gives users a lot more power over customizations.

**Comment by queue-tip** [comment]
Is this the same as what's in the `nightly` branch?

**Comment by mehalter** [comment]
The Heirline bufferline is on stable AstroNvim currently but it is an opt in feature. It came with v2.10.0. for v3 we will be removing bufferline entirely and use Heirline by default

**Comment by GersiD** [comment]
Dropping in to add that lualine is very wholesome and offers some easier to use (in my opinion) config options. Its pretty much as easy as adding a table with supported keywords. Not too sure what differs from Heirline but I thought I would add it since the package manager was basically overhauled. Lualine also has some pretty sick looking defaults. The auto setting is basically all that would be needed to make the base config look slick.

**Comment by mehalter** [comment]
I'm going to go ahead and close this issue because it's not tracking anything super important and the Projects provides a better roadmap
