### ISSUE TITLE
'< and '> not working in key mapping

### ISSUE THREAD

**Issue by rokonio** [AstroNvim/AstroNvim#1471]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.4.2

### Neovim version (>= 0.8)

v0.8.0

### Operating system/version

Ubuntu 22.04

### Describe the bug

The reference to the beginning and the end of the buffer ('< and '>) both return the 1st line instead.

### Steps to Reproduce

Have this keybing. When pressing Ctrl+Up in visual mode, it output line 1
```lua
v = {
    ["<C-Up>"] = {"<cmd>echom line(\"'>\")<cr>", desc="Return line number at the end of the current selection"}
}
```

### Expected behavior

Return correct line numbering

**Comment by mehalter** [comment]
We currently have the following as the default mappings for `>` and `<` to stay in visual mode with indenting. You can disabled these and take the default functionality in your user configuration. Here is a minimal `user/init.lua` example:

```lua
return {
  mappings = {
    v = {
      [">"] = nil,
      ["<"] = nil,
    },
  },
}
```

**Comment by rokonio** [comment]
Uhm this is not really what I asked about. I'm asking about the `'>` and `'<` aliases giving the wrong output when used in keybinding.

**Comment by mehalter** [comment]
Oh I see @rokonio sorry about that, I totally misread the issue. Regarding the binding you are referring to, there is something wrong with your keybinding. This behavior is the same as `nvim --clean` and then running `:vnoremap <C-Up> <cmd>echom("'>")<cr>`. I believe this is because `'>` and `'<` have the range of the previous selection so they aren't set until you leave visual mode. If you keep running the binding on different ranges you will see that it will be 1 visual mode selection off. You could change the binding to something like this:

```lua
v = {
    ["<C-Up>"] = {"<esc><cmd>echom line(\"'>\")<cr>", desc="Return line number at the end of the current selection"}
}
```

but this will end your selection. You could make it reselect the previous visual mode as well:


```lua
v = {
    ["<C-Up>"] = { "<esc><cmd>echom line(\"'>\")<cr>'<v'>", desc="Return line number at the end of the current selection"}
}
```

**Comment by mehalter** [comment]
You could also do this in Lua to not move in between normal and visual mode, something like this:

```lua
    ["<C-Up>"] = { function() vim.notify("Line: " .. vim.fn.line("v")) end },
```

`vim.fn.line("v")` will always return the line number of the other end of your visual selection that isn't the current cursor although the `'>` mark will always be your current cursor position in your last visual selection so I'm not sure what your goal of the binding is, you might actually want:

```lua
    ["<C-Up>"] = { function() vim.notify("Line: " .. vim.fn.getcurpos()[2]) end },
```

**Comment by rokonio** [comment]
Oh I see, thank you
