### ISSUE TITLE
Plugin nvim-ts-rainbow is no longer maintained

### ISSUE THREAD

**Issue by DiogoDoreto** [AstroNvim/AstroNvim#1509]
### Describe the new feature

I just updated my plugins and noticed a commit saying that `nvim-ts-rainbow` is no longer maintained. For now I don't think there's hurry to replace it, but still think it would be good to track and find a replacement eventually.

### Additional context

https://github.com/p00f/nvim-ts-rainbow/commit/ef95c15a935f97c65a80e48e12fe72d49aacf9b9

**Comment by mehalter** [comment]
Thanks for the heads up ts-rainbow has been removed from AstroNvim v3 which is slayed to be released at the end of this month along with Neovim 0.9

**Comment by GersiD** [comment]
Will it be replaced with the new maintained version? https://github.com/mrjones2014/nvim-ts-rainbow

**Comment by mehalter** [comment]
@GersiD there are still discussions about how the future of development for the plugin and if it will live there or go to a new organization. So until that decision happens I am going to leave it off AstroNvim

**Comment by GersiD** [comment]
That makes sense, thank you!

**Comment by dragove** [comment]
Maybe the performance of rainbow plugin should be considered. there are a batch of big json data in AI field. The rainbow plugin is very slow to start when encountering big files. (Maybe a bit of offtopic, I think there should be some default options to disable some plugins when encountering big files since big files not only makes starting neovim slow, but also slows moving cursor. Use `nvim --clean` makes moving much smoother)

**Comment by mehalter** [comment]
I'm going to go ahead and close this issue because it's not tracking anything super important and the Projects provides a better roadmap. For now I am not planning on adding `nvim-ts-rainbow` back even the currently maintained forks just because of the performance and uncertainty of future maintenance. Also it is easy enough to add on the user side

**Comment by GiorgosXou** [comment]
Maybe https://github.com/hiphish/rainbow-delimiters.nvim

**Comment by mehalter** [comment]
@GiorgosXou this space has been in so much flux, the one you linked seems to be the most developed solution, granted it's a rebrand of a different solution that happened a month or so ago. So who knows how long it will stay. But I have done a lot of experimenting with these plugins and none of them are remotely close to being stable enough for me to include them in AstroNvim core. All of these plugins are available in AstroCommunity so feel free to add it in your user configuration!
