### ISSUE TITLE
The LSP `tsserver` loads when opening a `denols` project with no package.json in the root

### ISSUE THREAD

**Issue by DeeGeeMan** [AstroNvim/AstroNvim#1536]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

NVIM v.0.8

### Operating system/version

macOS 12.6

### Describe the bug

I've followed the instructions for both [Typescript and Demo](https://astronvim.github.io/Recipes/advanced_lsp#typescript-typescriptnvim) LSP configurations.  However, `tsserver` loads when opening a `deno` project without an `package.json` file in the root folder.

### Steps to Reproduce

follow the steps in [Typescript and Demo](https://astronvim.github.io/Recipes/advanced_lsp#typescript-typescriptnvim)

### Expected behavior

`tsserver` to not load when open a `deno` root folder.

**Comment by DeeGeeMan** [comment]
I am unable to reproduce the problem in v2.10.1

**Comment by mehalter** [comment]
Can you please open this on the docs repo as this is unrelated to core AstroNvim

**Comment by DeeGeeMan** [comment]
Are you able to reproduce the problem?

**Comment by mehalter** [comment]
I can check when I'm back at my computer next week, so definitely open an issue on the docs

**Comment by DeeGeeMan** [comment]
Where is the docs repo?  I am not sure I understand how to report this issue on the docs.

**Comment by mehalter** [comment]
https://github.com/AstroNvim/astronvim.github.io

**Comment by mehalter** [comment]
@Firaenix Your configuration works fine-ish. There are several issues with it that should be addressed in regards to the `vtsls.lua` file: the `setup = { root_dir ... }`, that should just be removed. Also you will want to extend `opts` in the function rather than fully overwriting it, this will cause a lot of issues with our LSP integration. Also you will want to add `single_file_support = false` to the `vtsls` setup.

My guess if this isn't working is that there could be a nested project situation. Where `vtsls` is detecting a `package.json` file further up the directory chain.

I'm sorry for your frustration, this solution of using `root_dir` is extremely janky but is the recommended method in Neovim currently. If you want something a bit more sophisticated you could try out the AstroCommunity plugin pack for TypeScript and Deno. It does a much more complicated setup for detecting which one to start.

**Comment by Firaenix** [comment]
@mehalter Thank you very much for your suggestion about checking out the AstroCommunity plugin ([astrocommunity.pack.typescript-all-in-one](https://github.com/AstroNvim/astrocommunity/tree/16c6872d99a6e92edba7ab68ad5145a2308a05f1/lua/astrocommunity/pack/typescript-all-in-one) for those that stumble across this thread.). It seems to have solved all my issues. I've been struggling with this set up for months, so I appreciate your help and apologise for the frustrated comment. Maybe the Astro docs should suggest this community plugin, considering it seems to work so well?

Thanks again.
