### ISSUE TITLE
built-in doc/helpers: which-key & legendary

### ISSUE THREAD

**Issue by m-faith** [AstroNvim/AstroNvim#1564]
### Is your feature related to a problem?

Making it easy to learn the keybindings and available functions.

### Describe the new feature

https://github.com/folke/which-key.nvim and https://github.com/mrjones2014/legendary.nvim look like helpful things!

Legendary integrates with which-key, using existing whichkey tables.

Seems like a great helpful utility to have in a distro like this.

**Comment by mehalter** [comment]
This is a thing :)

**Comment by mehalter** [comment]
Yeah I am, but I don't think it needs to be added to core AstroNvim. Which key does a good job with learning bindings and telescope makes it easy to search

**Comment by m-faith** [comment]
Nice :)

I'm not familiar with either... they both just look cool... glad which-key is available, excited to make the leap in to AstroNvim!!!

**Comment by lougreenwood** [comment]
Sorry to comment on an old thread. I'll take this to Discord or open a new issue if there is no traction here 😅.

I just started to use `legendary.nvim`, I really, really like it - it feels more like a proper command palette (although it currently doesn't surface actual commands, see https://github.com/mrjones2014/legendary.nvim/issues/39) and takes away the pain of having to memorise keymaps (using which key can be tricky if one doesn't remember which key is the first in a mapping, or even if it's on leader or something else, etc).

However, for it to integrate with `which-key` there are some [requirements](https://github.com/mrjones2014/legendary.nvim/blob/master/doc/EXTENSIONS.md#which-keynvim), specifically:

> Automatically load key mappings defined by [which-key.nvim](https://github.com/folke/which-key.nvim) into legendary.nvim. For auto_register to work, which-key.nvim must be loaded on runtimepath before legendary.nvim initializes, but legendary.nvim must initialize the extension before require('which-key').register() is called. Alternatively, you can just pass your which-key tables to legendary directly.

This dependency chain for when when to load & register which key seems tricky, is it possible to handle this with `AstroNvim`? I guess I can make `which` depend on `which-key` with Lazy to handle the first part, but hooking into the whichkey setup to first setup legendary seems tricky.

Maybe this is an issue for legendary not being friendly to distro's and there could be a better way to allow the 2 to be integrated in a declararative way? I don't know 🤷.

**Comment by mehalter** [comment]
@lougreenwood the way I would do this is to lazy load legendary and then have which-key actually load it. Plugin specs like this:

```lua
    {
      "mrjones2014/legendary.nvim",
      opts = {
        extensions = {
          which_key = {
            auto_register = true,
          },
        },
      },
    },
    {
      "folke/which-key.nvim",
      config = function(...)
        pcall(require, "legendary")
        require "plugins.configs.which-key"(...)
      end,
    },
```

Fair warning we almost don't register anything with which-key so it will probably add nothing to your legendary. In v4 you will actually be able to build this out super easily because you would be able to access the system mapping table at any point very easily and you would be able to use that to build the legendary tables. This would be a great use case for AstroCommunity providing a not super trivial configuration that would be able to be used by anyone using AstroNvim to get legendary up and running. I will work on a MVP and show you what it would look like in v4

**Comment by mehalter** [comment]
for more details, we basically only use `vim.keymap.set` for all of our mappings. The only thing we register with `which-key` the "folder" or "section" names in the which-key menu. Everything else is done automatically because which-key can just understand vim keybindings

**Comment by lougreenwood** [comment]
Thanks @mehalter 🙇 !

I just tried the following config, but (assuming it's working, not sure how to test because...) it seems you're right and it doesn't add anything:

```lua
  priority = 10000,
    lazy = false,
    dependencies = { "kkharji/sqlite.lua" },
    keys = {
      { "<C-p>", "<cmd>Legendary<cr>", desc = "Toggle Legendary" },
    },
    opts = {
      extensions = {
        lazy_nvim = true,
        which_key = {
          auto_register = true,
        },
        smart_splits = true,
      },
    },
  },
  {
    "folke/which-key.nvim",
    dependencies = { "mrjones2014/legendary.nvim" },
    opts = {
      window = {
        position = "top",
        border = "single",
        margin = { 0.2, 0.2, 0, 0.2 },
      },
      layout = {
        align = "center",
      },

      -- Conflict with modes.nvim
      plugins = {
        presets = {
          operators = false,
        },
      },
    },
    config = function(plugin, opts)
      pcall(require, "legendary")
      require "plugins.configs.which-key"(plugin, opts)
    end,
  },
```

The reason I tried to integrate `which-key` & `legendary` was because I noticed some missing mappings, for example `<C-o>` & `<C-e>` for toggling and focusing `neo-tree` are missing in `legendary`, so I assumed it was because we set it via `which-key` in `astronvim`.... so I'll need to investigate this some more 🤔.

But TBH, if we set everything with `vim.keymap.set` then `legendary` should just work out-of-the-box... so maybe building the legendary tables won't be necessary, even w/ V4.

Also, as a side note - I do need to take a look at V4. I'd really like to try and wrap up my [tabline work](https://github.com/AstroNvim/AstroNvim/pull/1880) and see whether I can publish a PR targeting V4 before it's released since it may include breaking changes (for example changes to the highlight groups for the tabs so they can match buffers etc... I'm using it daily - it has a few missing features (but maybe those aren't needed for an MVP), but that's a topic for another thread, but let me know if this is something you're open to landing in V4, even if it's just groundwork with the breaking changes...

**Comment by lougreenwood** [comment]
Also, for reference, I figured out why `legendary` isn't picking up the `neo-tree` mappings. It's because `legendary` actually doesn't currently auto-load mappings from `vim.api.nvim_get_keymap` (because of previous schenegans).

https://github.com/mrjones2014/legendary.nvim/issues/258
