### ISSUE TITLE
Missing AstroNvim Command on Windows Version

### ISSUE THREAD

**Issue by tgh12** [AstroNvim/AstroNvim#1584]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.10.0

### Neovim version (>= 0.8)

NVIM 0.8.0

### Operating system/version

Windows 10

### Describe the bug

I try to install python Debugger and i use this command DapInstall python inside AstroNvim
but there is no command provided in AstroNvim windows version 
Also there are no PlugInstall command 
If there any suggestion to get full command dictionary inside AstroNvim for windows Version.

### Steps to Reproduce

Open file in Nvim
type :DapInstall python
there is no such command 

### Expected behavior

Show all the command inside AstroNvim

**Comment by mehalter** [comment]
Dap is not currently supported on Windows. You can check the documentation if you want to manually enable it and try to get it working.

https://astronvim.com/Recipes/dap

**Comment by aosterhage** [comment]
@mehalter What is the reason that its not currently supported? Is it related to https://github.com/jay-babu/mason-nvim-dap.nvim/issues/51? Will it be enabled if fixes for all adapters can be merged into mason-nvim-dap?

I'm asking because I'm interested in making this work. If there's more to do, I may look into it.
