### ISSUE TITLE
Prevent horizontal terminal from switching to other open file

### ISSUE THREAD

**Issue by BhuvanSA** [AstroNvim/AstroNvim#1591]
### Is your feature related to a problem?

Two or more instances of files opened Eg:
<SPACE> <f> <n>
Horizontal Terminal Triggered by using <SPACE> <t> <h>

Pressing <Shift> <j> in text editor window changes to a different file as current window

Doing the same thing while in terminal window does the same thing, Forcing users to close the terminal window and reopening it again 

### Describe the new feature

Prevent Horizontal Terminal window from switching to text edit mode

### Additional context

It happens when editing multiple files and using horizontal terminal at the same time

**Comment by mehalter** [comment]
I don't think I understand this feature request. Could you try explaining what you mean again? Sorry!

**Comment by BhuvanSA** [comment]
Sorry for bad explanation, I've attached a few screenshots to describe the issue

When editing multiple files with ToggleTerm horizontal split
Clicking other file while ToggleTerm window is active
Cause ToggleTerm horizontal split window to turn into a text-editor window

A feature to prevent this from happening or switching to top window when clicked

![1](https://user-images.githubusercontent.com/93479180/221358484-b437bdee-bf82-4e7d-8ce4-4c60531edda4.jpg)
![2](https://user-images.githubusercontent.com/93479180/221358487-52d09659-89c2-45b2-8c4c-fceaf0c7c64d.jpg)
![3](https://user-images.githubusercontent.com/93479180/221358490-8f41a846-1f20-42b3-b2d0-5a5d8a1ae499.jpg)

**Comment by mehalter** [comment]
Ohhh I see, yeah this will be a limitation of how `tabline` works in Neovim and how buffers/windows/tabs work. That `tabline` services every window and not just the editor windows. So there isn't a way for us to identify which is your main `editor` window and which ones you don't want to change. Sorry :( you will want to change focus to the window that you want to put the tab on before clicking on the tab. Because that tells `tabline` where to open it.
