### ISSUE TITLE
Mason not showing up

### ISSUE THREAD

**Issue by gabyx** [AstroNvim/AstroNvim#1601]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.11.8

### Neovim version (>= 0.8)

0.8.3

### Operating system/version

macOS 11.5

### Describe the bug

Sometimes it happens that `:Mason` does not lead to any visual window, not any error is just does nothing. I have the following almost default [`user/init.lua`](https://github.com/gabyx/astrovim/blob/main/init.lua) in place:

When I do 

```shell
rm -rf ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim
nvim
:PackerSync
:Mason
```

nothing happens.

`<leader>pa` acutally reacts and packer syncs and mason also does something but the Mason window does not appear. I am quiet a newbie with neovim etc. so I am a bit out of luck what the hack is wrong.
Any suggestion what to try or maybe look for in the `init.lua`?

### Steps to Reproduce

See above.      

### Expected behavior

Mason sync window pops up.

**Comment by gabyx** [comment]
Actuallt no command does anything: `MasonLog` also nothing...

**Comment by mehalter** [comment]
@gabyx did you restart after doing the packersync?

**Comment by gabyx** [comment]
Jeah, always, `:q!` and `nvim`

**Comment by mehalter** [comment]
Ok, I'll take a look tomorrow to see if I can replicate it with your user configuration and see what might be going on

**Comment by gabyx** [comment]
I tried tiredlessly to comment in stuff in my `init.lua` to a point where Mason always ran. Thats the latest main commit. And then I though jeah lets do a fresh install.
Deleted all the cash stuff `rm -rf ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim`

**Comment by mehalter** [comment]
@gabyx I would recommend trying out the v3 `nightly` to see if that helps with your issues. There is a migration guide in the docs (https://astronvim.com/nightly/Configuration/v3_migration). There are a lot of breaking changes as we greatly reduce the abstraction in our user configuration and we also ditch Packer and move to `lazy.nvim`. This is stable and ready to go right now, but is blocked by the delays of Neovim v0.9. For the time being we are leaving it also supporting Neovim v0.8 but that support will drop when it becomes stable.

I would recommend trying out migrating your configuration to the new version and see if that problem is still present. The lazy loading provided from Lazy.nvim is a lot more robust and stable than what we could hack together with packer. (also you can forget about ever remembering to run `:PackerSync` 😂 )

**Comment by mehalter** [comment]
You just need to set your `updater` settings to `updater = { channel = "nightly" }, in your user configuration and then restart and run `:AstroUpdate` to get the `nightly` version

**Comment by gabyx** [comment]
Ah that sounds great. I try to convert my init.lua to the v3 then.
I already took a look at NvChads thing, but that got me a bit complicated up, I guess AstroVim is really nice, giving reasonable defaults and anyway good control, with fairily good documentation! Keep the good work.

**Comment by gabyx** [comment]
@mehalter : Update works great now:

Using `neovim 0.9` with `brew install --head neovim`.

FYI: I then to use `nightly` in the config to run `AstroUpdate`. But it reported no changes. I though there might still be some troubles with the updater not switching branches. In then jsut checkout `nightly` branch and use now the following 
init.lua: https://github.com/gabyx/astrovim/blob/main/init.lua

I am wondering not related to astrovim: How should one make workspace related settings, like in `.vscode` to setup LSP differently, quite newbie with nvim still maybe you have here a direct link to where to look for.

**Comment by mehalter** [comment]
@gabyx this is a good plugin for this: https://github.com/folke/neoconf.nvim

You can just add something like this to your `plugins` configuration to add Neoconf as a dependency of `nvim-lspconfig`:

```lua
{
  "neovim/nvim-lspconfig",
  dependencies = {
    { "folke/neoconf.nvim", cmd = "Neoconf", config = true },
  },
}
