### ISSUE TITLE
Persistent theme with telescope theme picker

### ISSUE THREAD

**Issue by convers39** [AstroNvim/AstroNvim#1621]
### Is your feature related to a problem?

Currently, we set up the color theme in `init.lua`, for example: 

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/42597395/224518582-938dabe8-38e6-4ab7-804a-687315e0c6ac.png">

We can use telescope color theme picker to change theme quickly, but this change cannot persist as it will be overwritten when reopening neovim.

https://user-images.githubusercontent.com/42597395/224518776-c7d31cdd-386d-4593-9700-34876bcfd59b.mov

When changing a color theme we have to change the code directly (kind of weird that the commit msg is 'change color theme')

### Describe the new feature

It will be nice if the color theme picker can be persisted without changing the code.

(My apologizes if there were already a solution on this issue)

**Comment by mehalter** [comment]
This is not super intuitive necessarily. You could definitely implement this in some way if you wanted to or maybe there is a plugin available for this out there, but I think this would take an unnecessary amount of machinery without necessarily being needed by the masses. This would definitely make a bit more sense to do as an external plugin if someone wanted to make one rather than an AstroNvim specific feature.

This is also a relevant r/neovim thread: https://www.reddit.com/r/neovim/comments/ohn92m/how_to_change_colorscheme_and_make_it_persistent/

**Comment by luxus** [comment]
if you like changing themes a lot you can try my plugin :D
its maybe still buggy .. chatgpt wrote most of it..
https://github.com/luxus/colorful-times-nvim
