### ISSUE TITLE
Please provide a sample dockerfile to prepare Astrovim as container

### ISSUE THREAD

**Issue by SamPosh** [AstroNvim/AstroNvim#1700]
### Is your feature related to a problem?

I would like to develop inside the container.

Please provide dockerfile for it

### Describe the new feature

Like lunarvim dockerfile available in this place
https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/docker/Dockerfile.remote

Please provide a docker file for AstroVIM

**Comment by Gavus** [comment]
I use astronvim in a container but not in the way you are describing. A don't think a simple Containerfile will be much fun or helpful because on all the dependencies required by the mason installer, dependently on which packages you want to have installed.

Have you looked into https://github.com/89luca89/distrobox? That's the method I use , and i think its simpler for the end user and more flexible.
