### ISSUE TITLE
Treesitter syntax errors

### ISSUE THREAD

**Issue by DeeGeeMan** [AstroNvim/AstroNvim#1724]
### Describe the new feature

Why is `treesitter` displaying a syntax error for the `lua` code below?  I am only seeing this issue after migrating to AstroNvim v3.
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/21670040/229378813-83fa975b-b983-48ca-b502-b9be886e85d6.png">

**Comment by mehalter** [comment]
I'm not sure, try looking at the full error to see what might be going on with your treesitter
 It.may be that you need to reinstall some treesitter parsers. Maybe the `vim` parser. Also just a heads up, this is not a bug in AstroNvim since we do not do anything regarding treesitter functionality. I would definitely recommend joining the discord for questions like this as there are a ton of great community members who can help answer them :)
