### ISSUE TITLE
Can't change default shell to bash on Windows

### ISSUE THREAD

**Issue by yishiyuntuan** [AstroNvim/AstroNvim#1801]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

windows10

### Terminal/GUI

bash.exe、msys2

### AstroNvim Health

> /usr/bin/bash /s: No such file or directory

### Describe the bug

Unable to open terminal, open terminal, window outputs `/usr/bin/bash /s: No such file or directory` and closes immediately

### Steps to Reproduce

1. Runing gitbash or msys2
2. Press F7

### Expected behavior

-

### Screenshots

![image](https://user-images.githubusercontent.com/59228504/233577753-625a4cb7-6468-47b6-be24-8b19a0fdc0ce.png)

**Comment by mehalter** [comment]
@A-Lamia any idea on this one?

**Comment by A-Lamia** [comment]
Yeah not sure i can't get this to work.

**Comment by mehalter** [comment]
@yishiyuntuan how are you setting your shell in your user configuration? It seems like this is definitely a path issue in your configuration some where rather than a bug in AstroNvim. I am happy to try and help you debug in this issue as this will also help any future users with similar issues. Although most questions are asked on the Discord as there are many more users there who can help out.

I am going to go ahead and close this since I believe it's unrelated to the core AstroNvim codebase.
