### ISSUE TITLE
Enabling dap autocomplete via `cmp-dap`

### ISSUE THREAD

**Issue by jay-babu** [AstroNvim/AstroNvim#1928]
### Is your feature related to a problem?

no autocomplete in dap debugging windows

### Describe the new feature

https://github.com/jay-babu/dotfiles/blob/main/shell/.config/nvim/lua/user/plugins/cmp.lua

enable autocomplete in dap using the above configuration

**Comment by jay-babu** [comment]
if you are fine with this, i will attempt to create a PR

**Comment by mehalter** [comment]
This could be a good idea. It will be a bit tricky to make it modular enough since it takes a pretty decent amount of integration with CMP. I will take a look at adding this. If it doesn't fit super nicely this also could be a really good addition to AstroCommunity. I'll take a deeper look tomorrow and let you know @jay-babu

**Comment by mehalter** [comment]
Hm we won't be able to super easily add the cmp dependency conditionally since we do not enable DAP on Windows since the out of the box experience isn't super great. @jay-babu have you made any progress with that at all? Do all of the debuggers for the most part work? I know some were that weren't server based, but the server ones were not. I think until we have windows dap support in AstroNvim by default we won't be able to add this. But in the meantime we can add this to AstroCommunity super easily. I will look into making an AstroCommunity PR tomorrow.

**Comment by mehalter** [comment]
I am going to go ahead and close this. This will get merged in the next day or so :)
