### ISSUE TITLE
Beggining in "Delete mode" every time I open or create a file.

### ISSUE THREAD

**Issue by memeLordo** [AstroNvim/AstroNvim#1953]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04.2 LTS

### Terminal/GUI

zsh

## AstroNvim
  - INFO: AstroNvim Version: v3.17.0
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0

### Describe the bug

Recently I find a bug when program enter a "Delete" or "Insert" mode every time I open the file. I find that it happens only if my user library present, so I manually removed the files and commented the lines to find it's source (user/init.lua), and it happens to be lazy.nvim setup. I still don't know why it happens.

### Steps to Reproduce

1. Configure your user library based on user_example (which, btw, wasn't included in recent versions of Astrovim, I had to download it from the GitHub)
2. Open any file
3. Move your cursor in any direction (hjkl)
4. Text deleted

### Expected behavior

Just entering the "View" mode

### Screenshots

![изображение](https://github.com/AstroNvim/AstroNvim/assets/100208922/601dd13f-d073-4c82-bfa1-8d557001d127)

### Additional Context

Maybe it's because I'm using the WSL terminal or have a package conflict.

**Comment by mehalter** [comment]
Can you please share more detailed instructions to replicate the bug? You mention it's coming when your user folder is there and not when it's not? Can you share your user folder? I cannot replicate this. It sounds like a bug of your user configuration, but maybe I can help you debug it.

**Comment by mehalter** [comment]
I have taken a closer look and have verified that this is not an issue with core AstroNvim to my knowledge currently. I am going to go ahead and close this. If you are able to share your user configuration here I can still help you debug it probably. The Discord is also a great resource to ask questions and helping identify issues in your user configuration with the large number of users there who can provide help a lot quicker than I can individually :) If you do figure out what's causing it definitely drop a comment here to help out other users who might get into the same issue!


Also if you continue debugging and are able to show that it is a bug, also comment here and I can reopen this if it turns out to be something.
