### ISSUE TITLE
Helix-style, syntax-aware navigation keybindings

### ISSUE THREAD

**Issue by acarl005** [AstroNvim/AstroNvim#1986]
### Is your feature related to a problem?

Movement feels a little frustrating because there is some disconnect between my actual intention and the means to accomplish it. For example, if I want to move to the next parameter in a function signature, I can't directly press keys for "go to next parameter", I have to mentally map it to something like `f,` because I know a comma separates the parameters (and that only works when the parameters are on 1 line).

### Describe the new feature

Helix has a solution for this, which they call "[unimpaired keybindings](https://docs.helix-editor.com/keymap.html#unimpaired)". This, for example, maps `]a` to "Go to next argument/parameter" by utilizing tree-sitter.

It would be awesome to have similar keybindings in NeoVim!

### Additional context

Looks like there's another plugin by nvim-treesitter which might facilitate this, [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects).

**Comment by mehalter** [comment]
You can actually achieve this with the following plugin: https://github.com/nvim-treesitter/nvim-treesitter-textobjects

Here is my configuration that I use: https://code.mehalter.com/AstroNvim_user/~files/master/plugins/treesitter.lua

**Comment by mehalter** [comment]
I think for plugins like this are a great example of what can go into the AstroCommunity project rather than needing to get put into core AstroNvim. For now I think it's alright to leave it outside of core just because it can be so extensively configured to the users use case and can also easily end up conflicting with other core vim text objects as well as other plugins that provide text objects.

**Comment by acarl005** [comment]
This is awesome, thanks!!
