### ISSUE TITLE
Moving out the status bar to a separated package

### ISSUE THREAD

**Issue by Zeioth** [AstroNvim/AstroNvim#2022]
### Is your feature related to a problem?

It's not a big deal having the status bar implemented inside the distro, but I was thinking everything we can move from astrovim and make a package out of if, would make easier to the user (and for us) to manage the stuff. And I've observed the status bar has some complexity. Maybe it would be a good candidate.

The more simple and clean we keep the code, the easier will be to tweak.

### Describe the new feature

statusbar package. An astrobar package, or something.

### Additional context

Other people already did this. Could serve as reference: https://www.reddit.com/r/neovim/comments/14fl89l/lspprogressnvim_a_performant_lsp_progress_status/

**Comment by mehalter** [comment]
I have thought about this previously as well especially when first implementing the status API. The main thing is it wouldn't provide all that much benefit or increase usability in any way. The status API that we have built as it is now is strictly dependent on AstroNvim core utilities and would not work with a non AstroNvim Neovim setup. For this reason I have opted for now to leave it here rather than have a separate package that no one else would be able to use.

Eventually I would like to do something like this and refactor it out, but it would require some extremely large heavy lifting, a complete rewrite, and is a much longer term project at the moment.
