### ISSUE TITLE
current buffer closed behavior

### ISSUE THREAD

**Issue by ypli0629** [AstroNvim/AstroNvim#2030]
### Describe the new feature

the previous buffer should be choosed after closing the current buffer

**Comment by mehalter** [comment]
This seems to be a bug in `bufremove.nvim`. I think want we actually want to do is move away from this plugin. I have tested out `mini.bufremove` and it seems to be a great replacement for our use case and has the behavior that you want. This is currently fixed in AstroNvim Nightly and will be released soon :)
