### ISSUE TITLE
VSCode mapped features that I don't see present in AstroNvim's mappings

### ISSUE THREAD

**Issue by AthirsonSilva** [AstroNvim/AstroNvim#2108]
### Is your feature related to a problem?

I am in the process of slowly migrating from VSCode to Neovim, and some of the features I used frequently on my VSCode setup and that would be nice to have bult-in in AstroNvim are the ability to move a line up and down by pressing Alt + up/ down arrow key, Find/ Replace function and the ability to delete highlighted text without copying the deleted selection to clipboard.

### Describe the new feature

For the first feature, I found the :m function that can be used for this feature (ex.: :m +1 to move the selection one line up). My idea for the implementation of this function is basically each time a press a key to trigger this function and then follow with up/ down keys the integer parameter would increment/ decrement accordingly to the number of key presses.

For the second feature, I think that the :%s/target/replacement that replaces all text in the first parameter to have the value of the second parameter would make this possible.

For the last one would simply be a keybinding to use the "black hole register” to really delete text using "_d.

**Comment by mehalter** [comment]
Hey! Thanks for these requests! With AstroNvim we aim to have relatively minimal plugins to get the functionality that is necessary and then try to offload common desired customization/plugins to AstroCommunity. There are a few great plugins you might like:

Move lines: https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/motion/mini-move

Search/Replace: https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/project/nvim-spectre

It's super quick and easy to add these to your user configuration. Here is a minimal example of a `user/init.lua` file that sets up stock AstroNvim with just the additions you have requested:

```lua
return {
  plugins = {
    "AstroNvim/astrocommunity",
    { import = "astrocommunity.motion.mini-move" },
    { import = "astrocommunity.project.nvim-spectre" },
  },
}
```

As for the last one, this would be a great place to find a binding that works well for you and adding it to your `mappings` table in your user configuration as well. In core AstroNvim we try to keep all of our bindings following a very "vim-like" methodology to make it easy for people who know how to use vanilla vim/neovim so adding something like this could easily diverge from this and we tend to leave up to the user to add themselves rather than us enforcing non-vim-like bindings that aren't as intuitive and are strict memorization. Much easier for the user to decide which bindings they like in this case :)

I hope this helps get your editor to how you like it! The AstroCommunity project is super great and can help alleviate some of the configuration complexities especially for very commonly used plugins/colorschemes/etc.

**Comment by AthirsonSilva** [comment]
Thanks for the reply! One more thing I would like to know about adding new mappings to my config, I never did it before and, I couldn't find a tutorial for it after searching for some time. Can you provide a link for a guide or example of how it is done? I would appreciate it.

**Comment by mehalter** [comment]
Sure! Here is a good page in the docs: https://astronvim.com/Recipes/mappings#disable-telescope-lsp-mappings

Also lots of good information and comments can be found in the https://github.com/AstroNvim/user_example
