### ISSUE TITLE
how to set format  vue files replace default

### ISSUE THREAD

**Issue by ccc19357** [AstroNvim/AstroNvim#2120]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOs

### Terminal/GUI

item2

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.31.1
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

when  saving the vue file   i want html attributes like this 
![1689239035199](https://github.com/AstroNvim/AstroNvim/assets/19932721/ffe909cb-a793-4b4c-920a-b762520ddc08)

but it will be automatically formatted like this
![1689239057798](https://github.com/AstroNvim/AstroNvim/assets/19932721/42327cb9-3e0c-496b-91ec-94aaeeb391b9)

my config  repositories
https://github.com/ccc19357/astronvim-cgh-config

i install   ts vue  from astrocommunity.pack 
How to set to get the code style I want ?

hot to set format  vue files replace default

### Steps to Reproduce

none

### Expected behavior

none

**Comment by mehalter** [comment]
It looks like `volar` LSP uses `prettyhtml` for formatting which is based on `prettier` so you can use a `prettier` configuration file in your projects to configure the formatting: https://prettier.io/docs/en/configuration.html

Idk what options you want or even what are available so I can't help much more there. I also haven't used Vue or Volar before so idk if that configuration file will actually work. Sorry!

The Discord is probably a better place to ask questions since there are thousands of people there to answer :) https://discord.gg/AstroNvim
