### ISSUE TITLE
Use telescope master branch

### ISSUE THREAD

**Issue by karambaq** [AstroNvim/AstroNvim#2169]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.0

### Terminal/GUI

iterm-2

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.33.5
- Neovim Version: v0.10.0-dev-601+gd55d7646c
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Telescope master already have option to scroll preview to the sides:

https://github.com/search?q=repo%3Anvim-telescope%2Ftelescope.nvim%20preview_scrolling_right&type=code

However when I'm trying to use it in the configuration the error shows up:

```
Failed to run `config` for telescope.nvim

.../nvim/lazy/telescope.nvim/lua/telescope/actions/init.lua:74: Key does not exist for 'telescope.actions': preview_scrolling_right

# stacktrace:
  - /telescope.nvim/lua/telescope/actions/init.lua:74 _in_ **__index**
  - .config/nvim/lua/user/plugins/telescope.lua:221 _in_ **config**
  - .config/nvim/lua/astronvim/lazy.lua:43
  - .config/nvim/init.lua:10

```

### Steps to Reproduce

In telescope config:

```
      mappings = {
        i = {
          ["<c-t>"] = trouble.open_with_trouble,
          ["<c-e>"] = trouble.smart_open_with_trouble,
          ["<C-j>"] = actions.move_selection_next,
          ["<C-k>"] = actions.move_selection_previous,
          ["<C-L>"] = actions.preview_scrolling_right,
          ["<C-H>"] = actions.preview_scrolling_left,
        },

```

### Expected behavior

No errors

**Comment by mehalter** [comment]
The benefits of what we gain from pinning plugins to semantic versioning releases is stability rather than bleeding edge. This gives the user confidence when they run `:Lazy update` that their plugins are not going to randomly break because of breaking changes from the plugin developer. For example, there have been breaking changes since v0.1.2 in Telescope which was released last month (June 9, 2023). This is just part of the opinions that AstroNvim has decided to use to provide the most solid base for our users.

That being said, feel free to make changes in your user configuration to tune the editor to fit your needs! There are a few options, you can do:

1. Use AstroNvim nightly release channel, this will (1) not pin plugins and (2) get the fastest updates from us whether they are stable yet or not
2. You can use stable AstroNvim and disable the internal plugin pinning which will not guarantee that the AstroNvim code is up to date for all of the internal plugins by setting `pin_plugins = false` in your `updater` settings (https://astronvim.com/Configuration/updater)
3. You can disable the plugin pinning in your `plugins` table/`plugins/` folder on a per plugin basis. This is definitely the most "stable" approach as it minimizes the space that can randomly inflict breaking changes. Here is an example `user/init.lua` file that does this:

```lua
return {
  plugins = {
    { "telescope.nvim", version = false },
  },
}
```

**Comment by karambaq** [comment]
Thanks!
