### ISSUE TITLE
Move global neoconf.json outside of `lua/` folder

### ISSUE THREAD

**Issue by s1n7ax** [AstroNvim/AstroNvim#2180]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux Mint 21.1

### Terminal/GUI

Alacritty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.34.0
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- WARNING `node` is not installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Following is the path generated for neoconf global settings path

I added following print statement to `lua/plugins/lsp.lua:38`

```lua
{
    "folke/neoconf.nvim",
    opts = function()
    --
    --

      vim.print(">>", global_settings and string.rep("../", depth):sub(1, -2) .. global_settings)
      return { global_settings = global_settings and string.rep("../", depth):sub(1, -2) .. global_settings }
    end,
  }
```

Result:
```
>>
../../../../home/s1n7ax/.config/astronvim/lua/user/neoconf.json
```

### Steps to Reproduce

1. Add neoconf.json to `~/.config/astronvim/lua/user/neoconf.json`
2. Add following content to the file
```json
{
  "neodev": {
    "library": {
      "enabled": true,
      "plugins": true
    }
  },
  "neoconf": {
    "plugins": {
      "lua_ls": {
        "enabled": true
      }
    }
  },
  "lspconfig": {
    "lua_ls": {
      "Lua.format.enable": false
    }
  }
}
```
3. Open a project with a `.lua` file `mkdir test && cd test && git init && nvim test.lua`
4. Add some content
5. move the cursor to first line
6. `:vsp` split window and move the cursor to last line
7. Jump back to first window and run `:Format`

### Expected behavior

Expected:
Cursor in the new window should still be at last line

Actual:
File resets and cursor pos jumps to first line

**Comment by s1n7ax** [comment]
It's good to have it within the user config but having a json file inside lua module directory is a bit weird IMO.

**Comment by mehalter** [comment]
Yeah this is to keep it away from the global files. This will actually be resolved in AstroNvim v4 when we get rid of the user configuration folder all together and this will be in the correct place

**Comment by s1n7ax** [comment]
I think the title I have put was misleading. The issue here is when I put some configuration at `~/.config/astronvim/lua/user/neoconf.json` the configuration is not applied.

**Comment by mehalter** [comment]
@s1n7ax I just verified that on stock AstroNvim this does work, just make sure you have it in the correct place. You can also verify this by running `:Neoconf global` to get the file that it is using as the global configuration. If you have your configuration in `~/.config/astronvim/` for example then this would be `~/.config/astronvim/lua/user/neoconf.json`.

**Comment by s1n7ax** [comment]
This is related to https://github.com/AstroNvim/AstroNvim/issues/2178. I basically don't want buffer to be reload on format. I think I have the file at correct place but it seems formatting a file still reloads the file. 

https://github.com/AstroNvim/AstroNvim/assets/18459807/1049b1c7-932c-477f-b8fd-87acea45f07d

**Comment by mehalter** [comment]
https://asciinema.org/a/dq9OaAbISbH9wl4kQSaEMSchM

Here is an example showing the neoconf.json file in the `user/` folder working appropriately.

You can also use the `lsp` table to do global changes which is probably safer in the long run:

Here is an example `user/init.lua` file:

```lua
return {
  lsp = {
    config = {
      lua_ls = {
        settings = {
          Lua = {
            format = { enable = false },
          },
        },
      },
    },
  },
}
```

Or you can put this in `user/lsp/config/lua_ls.lua`:

```lua
return {
  settings = {
    Lua = {
      format = { enable = false },
    },
  },
}
```

**Comment by mehalter** [comment]
@s1n7ax you can also sanity check that your settings are being applied by running `:Neoconf show` to see what it is actually applying

**Comment by s1n7ax** [comment]
![image](https://github.com/AstroNvim/AstroNvim/assets/18459807/fec88413-354d-4249-8e56-985174cc6dc4)

**Comment by mehalter** [comment]
Awesome, if that is showing up then Neoconf is getting the values and we can't do much else on the matter. Sorry! If it's not working for you I would recommend doing it directly in LSP Config.

AstroNvim v4 will be resolving the deeper issue which will be that this file will live in the correct place. I'll leave this issue open until v4 is released.

**Comment by s1n7ax** [comment]
@mehalter I will dig into this in a free time. I started using Astronvim primarily. Awesome architecture. Love the fact that the everything in core can be changed. Never realized how valuable lazy nvim merging capability is until I used this.

**Comment by mehalter** [comment]
That's awesome, I'm glad you are enjoying it! Hopefully you will like the new restructuring in AstroNvim v4 :joy: We are moving to entirely configured through lazy.nvim. The AstroNvim repository will simply be it's own `plugins/` repo and users will just simply have their own neovim configuration with lazy that just imports our plugins. This will do a few things:

1. Move configuration outside of `user/` folder and into the normal location with no more fear of overwriting internal AstroNvim code
2. Installing a user configuration will go from 2 git clones (first astronvim, then your user configuration to the `user/` folder) to just a single clone of your configuration to `~/.config/nvim`
3. Use Lazy.nvim to deliver updates rather than our own updater
4. Allow all configuration options to be set through plugins enabled AstroCommunity to have much more power in what it delivers to let plugin specs more succinctly modify stuff like core mappings, LSP configuration options, etc.
5. Gives us the ability to further modularize our setup by providing some house made plugins for functionality, mainly AstroCore (the main utilities), AstroLSP (our LSP configuration engine), and AstroUI (our statusline stuff and UI elements like icons)

This will also allow us to remove some of the abstraction and stuff like managing configuration stuff on our own and dealing with manually overriding folders like this with Neoconf, it will just rely on the default neovim folders. This should greatly decrease the abstraction we are adding and make it easier for the user to realize what's going on and have a much more "vim" like approach to configuration.

This is quite similar to how LazyVim does things as well, we will just have a quite different architecture under the hood of providing some of our own plugins for functionality rather than wrapping it all up inside of AstroNvim :)

**Comment by mehalter** [comment]
Not sure the timeline on releasing all of this yet, it's still got a bit of development that needs to happen but very excited to get this out there :D And hopefully people don't hate that this is going to be some significant changes to the user configuration set up :(

**Comment by stillwu** [comment]
By the way, I'm confused why there is no code suggestion about 'rust-analyzer' and 'gopls' in 'neoconf.json'. But setup 'rust-analyzer' with 'neoconf.json' still work well. Here comes screenshot:

![image](https://github.com/AstroNvim/AstroNvim/assets/76519998/80eab3fa-bbd6-4bb3-a469-0028461bcb15)

appreciate for any reply.

**Comment by mehalter** [comment]
@stillwu `rust_analyzer` seems to work for me perfectly:

![2023-08-19_06:16:37_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/0b40f066-1da5-4ef4-acb1-03459cbcfdc6)

In the screenshot you sent you already have `rust_analyzer` as a key and therefore it will not give it to you in the completion because that would not be valid `json` since you would be repeating a key.

`gopls` it looks like might not have completion. This is not something I know since I do not develop or maintain the plugin, but it looks like not every language server is supported. `marksman` for example doesn't seem to have completion. My guess is not all language servers properly implement the completion.

**Comment by stillwu** [comment]
@mehalter Sorry, my bad for the screenshot. But it still has no completion and I promise I do not change anything about 'astrocommunity.pack.rust', 'lspconfig' or something else.

<img width="947" alt="微信截图_20230819183257" src="https://github.com/AstroNvim/AstroNvim/assets/76519998/fc45b669-dc40-4699-845c-281d82e4d744">

But if it can't be solved, let it go, whatever.

Thanks again.

**Comment by mehalter** [comment]
Bad bot 😅 added the correct labels to block the stale bot....

**Comment by mehalter** [comment]
AstroNvim v4 public beta period has begun and the docs are nearly finished being written. I am going to start closing stuff as they get finished on v4 since it is pretty close to being released in some way. Anyone that comes across this before the release and wants to test v4 check out the [#v4-testing channel](https://discord.com/channels/939594913560031363/1176578004630130789) on the official AstroNvim Discord.
