### ISSUE TITLE
An error occurs when opening a file in ~/.config/nvim/lua to nvim after installing Astronvim.

### ISSUE THREAD

**Issue by Errorman76** [AstroNvim/AstroNvim#2304]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.5.2

### Terminal/GUI

iterm2

### AstroNvim Health

AstroNvim Version: v3.36.12
Neovim Version: v0.9.2
OK Using stable Neovim >= 0.8.0
OK git is installed: Used for core functionality such as updater and plugin management
OK open is installed: Used for gx mapping for opening files with system opener (Optional)
OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
OK node is installed: Used for mappings to pull up node REPL (Optional)
WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
OK python3 is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Error opening file: vim/_editor.lua:0: nvim_exec2()..BufReadPost Autocommands for "*": Vim(append):Error executing lua callback: ...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:

### Steps to Reproduce

1. Install AstroNvim
2. Open files inside ~/.config/nvim/lua to nvim

### Expected behavior

File must be opened normally

### Screenshots
![image](https://github.com/AstroNvim/AstroNvim/assets/20393205/9df93557-adb1-4b77-8044-a6b51ef8a70e)

_No response_

**Comment by mehalter** [comment]
What filetype are you trying to open. It looks like an issue with the treesitter parser that is trying to get loaded. The first step would be to figure out what parser is borked since it's not being reported in the error and ten trying to reinstall it with `:TSInstall`. For instance if this is happening with Lua files then you would do `:TSInstall lua` and it will prompt you if you want to reinstall and you want to say yes.

**Comment by Errorman76** [comment]
Thank you for your help. The problem was resolved after installing lua parser.
