### ISSUE TITLE
In-editor documentation

### ISSUE THREAD

**Issue by vclemenzi** [AstroNvim/AstroNvim#2314]
### Is your feature related to a problem?

Yes

### Describe the new feature

Astrovim in addition to offering an excellent configuration of neovim, offers a documentation on how to use the configuration on the site. Often, however, if you are in a coding session and don't know how to do something, it can be boring to have to open the site. For this reason I want to propose reporting the documentation within a neovim help file. It might be called `editor` or `astrovim`. I can possibly help bring the documentation back to the editor with a pull request if you like the idea

**Comment by mehalter** [comment]
This has actually been implemented already in the upcoming v4 release! It will have all of the configuration documentation in vim docs as well as full Lua language server completion with docs as well :)

Looking forward to that release! Timeline should align with the release of Neovim v0.10!

**Comment by vclemenzi** [comment]
Oh, my bad! Thank you for the response and congratulations for the excellent config!

**Comment by mehalter** [comment]
@vclemenzi if you want to check out some sneak previews to what I described above:

![2023-10-02_13:53:20_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/4b84c72b-4655-4719-ae57-8b7a23c1c509)
![2023-10-02_13:55:00_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/6be6e319-6b0e-4386-8481-549264e5c146)
![2023-10-02_13:55:55_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/e41ae06d-af36-43be-a37b-af01b0630ea7)

**Comment by vclemenzi** [comment]
Looks great!

**Comment by mehalter** [comment]
This will have auto completion of all the nested options even down to the auto completion of full language server options as well. Then Lua API documentation in the `:help` menu along with the configuration details and such.

This also comes with a large modularization to individual plugins for configuration internals rather than us having a bespoke configuration. It will all be configured through lazy `opts` tables like any other plugin :) We will have [AstroCore](https://github.com/AstroNvim/astrocore), [AstroUI](https://github.com/AstroNvim/astroui), and [AstroLSP](https://github.com/AstroNvim/astrolsp)

**Comment by mehalter** [comment]
This will also empower AstroCommunity to be able to have full control over user configuration rather than being limited to just configuring plugins
