### ISSUE TITLE
Astronvim embedded interactive floating help menu / cheatsheet

### ISSUE THREAD

**Issue by Tal500** [AstroNvim/AstroNvim#2346]
### Describe the new feature

I think it will be friendly to the user if there will be an interactive cheatsheet popup by a key, or some kind of "basic help menu".

The first one needs no explanation, but I'm not a huge fan of it, rather I believe the latter one is better.

The menu should be in my opinion something like the UI of Telescope, when the topics(normal mode, edit mode, telescope, git, and all the other basic vim and astronvim capabilities) are on the left selection menu, while their explanation is on the main box to the right. A better UI is possible, but this is a start.

Do you think such a thing is needed? A tutorial can be embedded the same way.

**Comment by mehalter** [comment]
There are telescope menus such as `:Telescope  keymaps` to easily browse available mappings based on binding or description

**Comment by mehalter** [comment]
There are also cheatsheets with `which-key` as you type. Which leads you through menus key by key

**Comment by Tal500** [comment]
> There are telescope menus such as `:Telescope keymaps` to easily browse available mappings based on binding or description
> There are also cheatsheets with `which-key` as you type. Which leads you through menus key by key

While they are very useful to me, as a new experience of Nvim is hard, it would be nice to have easy manuals. There are great ones in the AstroNvim website, but Vim likes to put manuals inside of itself. It doesn't need to be super geeky only, and NVChad Cheatsheet UI brought me the idea that help can be also formatted nicely.

**Comment by mehalter** [comment]
Yeah I could see this being a nice feature. I don't quite think the NvChad cheatsheet is the easiest to follow since it just dumps everything on the screen at once and also requires a large screen anyway to print all mappings. It also has quite strong limitations based on how mappings are set to be able to be displayed in it rather than actually applying to all mappings.

 AstroNvim provides leader based mappings 99% of the time so the which-key menu seems to be a lot easier to follow and guides the user through the available options.

If someone wanted to implement something that fits their needs better, I would definitely be open to PRs. It seems like it would be better for the ecosystem to formulate it as a plugin rather than baking it into AstroNvim though so it would be accessible to others. But if we wanted it we could make our own plugin similar to what NvChad does.


A built-in tutorial, on the other hand, would also be super nice. Similar to vim tutor to help guide new users like what's in the documentation website. It would also be awesome if someone wanted to build one and contribute it. 😄
