### ISSUE TITLE
Erorr when trying to open a new file from telescope with filetree and alpha open

### ISSUE THREAD

**Issue by rawnly** [AstroNvim/AstroNvim#2426]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 14.2.1

### Terminal/GUI

wezterm

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.41.1
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu-go` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When I open a file from telescope, with alpha.nvim and filtree open, an error is thrown.
Once the error is dismissed if i open the file it loses the syntax highlight / LSP etc

### Steps to Reproduce

With alpha.nvim open, 

1. open the file tree  
2. open a new file from telescope

### Expected behavior

Open the file with syntax highlight

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/16429579/0c33e37a-6462-4987-bd70-486a1e236bcd)

### Additional Context

https://github.com/rawnly/nvim-config/tree/work-profile (check the `work-profile` branch please)

**Comment by mehalter** [comment]
Thanks for sharing your config as this really helps with replication! ❤️ 

I can replicate it with your config and cannot replicate in core AstroNvim which makes me lean towards the problem being on your end. I did some debugging to see where this bug comes up and deduced it down to when you have [`nvim-telescope/telescope-frecency.nvim`](https://github.com/nvim-telescope/telescope-frecency.nvim) installed. It looks like there is a bug somewhere in the interaction between telescope-frecency and alpha. Sadly that's about as far as I can take you on this one. I did create this minimal `repro.lua` file that you can use to report the bug elsewhere to hopefully get your issue resolved!

```lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	{
		"nvim-neo-tree/neo-tree.nvim",
		branch = "v3.x",
		dependencies = {
			"nvim-lua/plenary.nvim",
			"nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
			"MunifTanjim/nui.nvim",
			-- "3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
		},
	},
	{
		"goolord/alpha-nvim",
		dependencies = { "nvim-tree/nvim-web-devicons" },
		config = function()
			local dashboard = require("alpha.themes.dashboard")
			dashboard.config.opts.noautocmd = true

			require("alpha").setup(dashboard.config)
		end,
	},
	{
		"nvim-telescope/telescope.nvim",
		tag = "0.1.5",
		dependencies = { "nvim-lua/plenary.nvim" },
	},
	{
		"nvim-telescope/telescope-frecency.nvim",
		config = function()
			require("telescope").load_extension("frecency")
		end,
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})
```

Steps to reproduce:

1. `nvim` - open neovim
2. `:Neotree` - open neo-tree
3. `:Telescope find_files` - find files (with focus in neo-tree
4. select a file

See that syntax highlighting is not present, if you try to close a buffer or quite neovim you will then see the lingering error that you showed here of the `Invalid buffer id: 1`.

Sorry I can't do much else from here! Just recommendation when reporting things upstream is always to create a minimal config like above that removes all other variables and then report it without mentioning you use a distribution or else they will always close and say "it's probably their fault". Good luck!

**Comment by rawnly** [comment]
Thank you for the help! I'll try to report to telescope / alpha and see what happens then!
