### ISSUE TITLE
Add WSL support to system open

### ISSUE THREAD

**Issue by NichloasChiu** [AstroNvim/AstroNvim#2452]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [x] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

windows10

### Terminal/GUI

wsl

### AstroNvim Health

```
AstroNvim ~
- AstroNvim Version: v3.40.3
- Neovim Version: v0.10.0-dev
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

Hello, excuse me. I am using the wsl system in the terminal terminal in windows 10, using Astro, and I found that the "O" key in the neo-tree cannot effectively recognize the wsl when opening the file with the system, and it is recognized as a linux system, resulting in an invalid operation. Do you think about fixing this problem or telling me how to solve this problem, I believe that there are many users who use WSL

### Steps to Reproduce

Open Neovim, then Leader<E>, press "O", it is not recognized

### Expected behavior

Neo-tree issue in WSL

**Comment by mehalter** [comment]
Seeing that you are using neovim 0.10 nightly (which is unsupported), you are probably using the core `vim.ui.open` function rather than the one in AstroNvim. I have made our function (used in Neovim 0.9 and lower) to align more with the new 0.10 feature. It does require `wslview` which may or may not need to be installed separately. I don't use WSL so I'm not sure if it's available by default.

**Comment by NichloasChiu** [comment]
Thank you very much for your answer, I tried again with apt install wslview and updated to the latest Astro, the problem has been solved. It would be nice if you could judge wsl without downloading wslview or you could force it to open with windows, but it's not very important, after all, wslview is also very easy to use, this problem has been bothering me for a long time, thank you very much.

**Comment by mehalter** [comment]
No problem at all. Definitely understand your request. Like I explained in my previous message, you are using the core Neovim feature `vim.ui.open` so any requests for that would go to core neovim/Neovim rather than here. We won't be developing this function anymore. The update I did was purely back porting the full Neovim core implementation that came out recently.
