### ISSUE TITLE
Support for Code Suggestion tools

### ISSUE THREAD

**Issue by 1stdevfriend** [AstroNvim/AstroNvim#2459]
### Describe the new feature

Numerous developers utilise advanced coding aids such as GitHub Copilot, tabbing, and other code suggestion tools. Is it possible for us to implement similar functionalities?

**Comment by mehalter** [comment]
Yup! Check out documentation for how to [Manage a User configuration](https://docs.astronvim.com/configuration/manage_user_config/) and add [Custom Plugins](https://docs.astronvim.com/recipes/custom_plugins/)

Also check out AstroCommunity for the easy sharing of plugin configurations: https://github.com/AstroNvim/astrocommunity

**Comment by mehalter** [comment]
Here are some examples of codeium, copilot, tabnine code completion plugins: https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/completion

As well as stuff like a ChatGPT plugin: https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/editing-support/chatgpt-nvim

Basically, this isn't functionality we are interested in adding to core AstroNvim because it is out of scope. AstroCommunity is there so the community can easily add features, share them, and collaborate to improve them. It isn't maintained by any core AstroNvim devs outside of sanity checks to make sure no malware, and is completely led by the community.

**Comment by 1stdevfriend** [comment]
Thank you so much!
