### ISSUE TITLE
Mason-null-ls install on every launch

### ISSUE THREAD

**Issue by ForAeons** [AstroNvim/AstroNvim#2487]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux Mint 21.3 x86_64, macOS 14.3 23D56 arm64

### Terminal/GUI

alacritty, kitty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.44.2
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Every time I open neovim, I get prompted with "mason-null-ls installing xxx", "mason-null-dap installing xxx". Even if I leave my nvim open for a long time (to let it install), the prompt returns when I reopen neovim.

This also happens on my macos system which uses the same user config. Interestingly, it is installing different stuff.

### Steps to Reproduce

1. Open a file with neovim: `nvim <file>`

### [Configuration files](https://github.com/ForAeons/astronvim_config)
- `~/.config/nvim/lua/user/plugins/astrocommunity.lua`
```lua
return {
  "AstroNvim/astrocommunity",
  { import = "user/plugins/community" },
}
```

- `~/.config/nvim/lua/user/plugins/community/language.lua`
```lua
return {
  { import = "astrocommunity.pack.bash" },
  { import = "astrocommunity.pack.cpp" },
  { import = "astrocommunity.pack.docker" },
  { import = "astrocommunity.pack.go" },
  { import = "astrocommunity.pack.html-css" },
  { import = "astrocommunity.pack.java" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.pack.python" },
  { import = "astrocommunity.pack.rust" },
  { import = "astrocommunity.pack.tailwindcss" },
  { import = "astrocommunity.pack.toml" },
  { import = "astrocommunity.pack.yaml" },
}
```

### Expected behavior

Install once. No more installs on future launches.

### Screenshots

# Linux Mint System:
![Screenshot from 2024-03-12 15-28-48](https://github.com/AstroNvim/AstroNvim/assets/81742181/f522c408-0397-4812-8181-0a99ab2e3048)

# MacOS System:
<img width="466" alt="Screenshot 2024-03-12 at 4 40 37 PM" src="https://github.com/AstroNvim/AstroNvim/assets/81742181/cfaee2e6-a5e9-4f60-bc7e-7f71c3fc403f">

**Comment by mehalter** [comment]
This will happen if the Mason installation fails. That could be because you have missing dependencies for doing the installation like `luarocks` or something. Check details in the Mason UI with `:Mason`

**Comment by ForAeons** [comment]
Thanks a lot 👍🏻

**Comment by mb720** [comment]
Using AstroNvim on Arch Linux since yesterday (v4.25.0), I also encountered this after activating the file `community.lua` and thus importing `astrocommunity.pack.lua` by removing the line

>if true then return {} end

There are no other changes to AstroNvim's config.

Running `nvim test`, I see the same notifications saying
>[mason-null-ls] installing stylua
>[mason-null-ls] installing selene

Running `:Mason` shows no obvious issues:

    Installed
      ✓ lua-language-server lua_ls
      ✓ taplo

Since I have no experience with Mason, I don't know how to resolve this.

---
P.S.: Thanks for AstroNvim, it's impressive how well it works and the features it includes. I had a great time programming using `astrocommunity.completion.copilot-lua` and `astrocommunity.pack.rust`.

**Comment by mehalter** [comment]
Mason enables when you open a file. If you just run `nvim` it won't load until you edit a file. If it didn't load when you edit a file then it wouldn't work :)

**Comment by mb720** [comment]
Thanks for the very quick response!

Some observations:

* When I run just `nvim`, the notifications don't appear (all good).
* When I then use that Neovim instance to open a file (a new one or a recent one) the notifications don't appear (all good).
* When I use the "Bookmarks" (SPC f '') entry in the AstroNvim start menu, I get the notifications again.
* When running `nvim test` or `nvim some_other_file` (like wxiaoyun did) I get the notifications.

Is it normal that the notifications appear in the last two cases?
From your prior messages it seems that selene and stylua didn't get properly installed but there's no error in `:Mason`.

**Comment by mehalter** [comment]
Yup that is correct. You should open `:Mason` to see if there is an error

**Comment by mehalter** [comment]
Just for clarity, if it finished installing with no errors, then it wouldn't try to install when the plugin loads. So you can see the status in `:Mason`. If it was successfully installed then it would show a checkmark next to it. If it's an error, an X, if it's installing then some spinning arrows

**Comment by mehalter** [comment]
Also a good place to ask questions is the discord server where more users will be present to provide guidance

**Comment by mb720** [comment]
I figured out what the issue was after calling `:MasonLog` which shows these entries:

    [ERROR Fri 30 Aug 2024 10:10:11 PM CEST] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=stylua) error=spawn: unzip failed with exit code - and signal -. unzip is not executable
    [ERROR Fri 30 Aug 2024 10:10:19 PM CEST] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=selene) error=spawn: unzip failed with exit code - and signal -. unzip is not executable

Alright, `unzip` is not installed, that's easily fixed with `pacman -S unzip`.

I'm not the first one that ran into this issue:
  * https://github.com/williamboman/mason-lspconfig.nvim/issues/10
  * https://github.com/nvim-lua/kickstart.nvim/issues/151

In hindsight, I could have also found out if I had called `:Mason` *earlier* after opening a file. It seems Mason's errors are only shown in `:Mason` if they happened a few seconds ago.

Thanks for your help, I'll use Discord the next time. On the other hand, I'm always happy to find discussions about issues I have on the web via search engines. And I think Discord chats aren't indexed by search engines.
