### ISSUE TITLE
Where is the AstroNvim v3 documentation?

### ISSUE THREAD

**Issue by eagle-tex** [AstroNvim/AstroNvim#2529]
Inside the documentation of the current version (v4), could you please provide a link to the v3 documentation?
Some of us might still need to refer to it, since the migration to v4 is not yet functional.

**Comment by mehalter** [comment]
We have it dropped here: https://docs.astronvim.com/v3

**Comment by mehalter** [comment]
Also not sure exactly what you mean by v4 not being functional yet. It is fully functional and ready for production use. It has been in development since July, 2023 with core devs testing it since August, 2023 and Public beta of many people since the beginning of 2024. So there are many months of public testing and >10 months of less public testing. Also the migration guide is complete and the docs are also complete

**Comment by eagle-tex** [comment]
Sorry, I mispoke. I installed v4 and was getting errors with treesitter (you provided a solution in another issue I raised), nvim-dap plugin.
I should have said "I haven't been able to make it work on my computer yet".
I wasn't trying to put shade on your work (you and the other devs, testers) in any way. Thanks to you all for your hard work and dedication.
