### ISSUE TITLE
How to configure c++ tools?

### ISSUE THREAD

**Issue by giulianoc** [AstroNvim/AstroNvim#2554]
Hi,

**Comment by giulianoc** [comment]
Hi,
sorry I sent the issue when the description was not completed yet.
Here follow more details.
I'm a c++ programmer and I would to configure c++ tools like:
    - clangd
    - cpplint
    - clang-format
    - cmake-language-server
    - cmakelang
    - cmakelint
    - cpptools
Could you please tell me a detailed description on how to make this configuration?
Best regards

**Comment by mehalter** [comment]
Hey! We try to keep questions and discussion centralized on Discord since people tend to not check the GitHub issues. There is a great help forum there and many users who can help answer questions: 

https://discord.astronvim.com/

One way I would recommend quickly getting set up is to use the AstroCommunity C++ language pack! Check out AstroCommunity here: https://github.com/AstroNvim/astrocommunity
