### ISSUE TITLE
Can't get <C-s> mapping to work in insert mode

### ISSUE THREAD

**Issue by Viterkim** [AstroNvim/AstroNvim#2570]
Sorry if this is wrong, everything else works great in astronvim 4!

I can't seem to get <Control s> to work in insert mode for saving.

https://github.com/Viterkim/astro4/blob/main/lua/plugins/mappings.lua#L141
It seems like something is already bound on <C-s> in insert mode maybe?, but shouldn't this overwrite it?
Tried searching around but couldn't find anything, both me and my friend have this issue. Do we bind it somewhere else?

Thanks

**Comment by mehalter** [comment]
In our mappings table we normalize casing based on the official vimdoc keycodes, letters after `<C-` are always shown as capitalized so that's how our casing is and I would recommend you use yours as well to make sure you actually overwrite any keys that we may be setting in default Astronvim. Also we have backported a new default mapping that is coming in Neovim v0.10 which you can disable in AstroLSP, here is an example:

```lua
return {
  "AstroNvim/astrolsp",
  opts = {
    mappings = {
      i = {
        ["<C-S>"] = false
      }
    }
  }
}
```

**Comment by mehalter** [comment]
Also us backporting this mapping actually does break our own default mapping of `<C-S>` being mapped to save. I have reverted this and will release soon. So the above code will be unnecessary and your own mapping of `<C-S>` for save is also unnecessary since it's a default

**Comment by Viterkim** [comment]
Great thank you!
