### ISSUE TITLE
vue file save

### ISSUE THREAD

**Issue by zmy20220416** [AstroNvim/AstroNvim#2592]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [ ] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

windows 11

### Terminal/GUI

neovide

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.7.0
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.9.5
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `rundll32` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu/gdu_windows_amd64.exe` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I added the community package of vue in community.lua, but it cannot be saved correctly in the vue file. For example, if I delete a line, when I save, the deleted line will still be displayed.

### Steps to Reproduce

1. Open a vue file
2. Delete a line of code
3. Save the file

### Expected behavior

Saving works fine

### Screenshots

![bug](https://github.com/AstroNvim/AstroNvim/assets/123053563/45bdbc97-b09e-4e74-a26c-051b3d045793)

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
I followed the replication instructions and they were not sufficient enough to replicate the problem.

1. The provided `repro.lua` is not sufficient and you should _not_ check the box that says "I can replicate the bug with the minimal `repro.lua` provided below". This list is a checklist of things you should do _before_ opening an issue
2. You need to provide more information to replicate. You say you have added the `vue` pack, but you have also added a lot more, please provide more details and if not a minimal `repro.lua`, at least your configuration. If you share your configuration there is no guarantee we will fix your configuration though and providing a minimal `repro.lua` will guarantee the fastest and most controlled path to replication
3. You should probably provide an example project. I opened some random Vue project I pulled from GitHub, installed the `vue` pack and it works fine. You should provide a Vue project that you have verified replicates the issue, these projects may have different dependencies and things

Hope this helps point you in the correct direction! I will go ahead and close this as there isn't anything actionable. If you are able to provide some more details I can re-open this issue. Chances are this is probably just a bug in AstroCommunity rather than AstroNvim so I can also do some triage if you provide more information and transfer this issue accordingly
