### ISSUE TITLE
Bug: The nerd Icon became `E` after the cmd was canceled.

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#2603]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

macos 14.5

### Terminal/GUI

Wezterm

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v4.7.2
- Neovim Version: v0.10.0
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `rg` is installed: Used for Telescope `live_grep` picker, `<Leader>fw` and `<Leader>fW` by default (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu-go` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

The Lsp Icon became invalid after the cmd was canceled.

https://github.com/AstroNvim/AstroNvim/assets/51357674/2076f757-a9a0-438d-a0f1-9acaf0b67b45

### Steps to Reproduce

1. Find an statement with an error
2. press `:` keyboard
3. press `esc` exit the cmd

### Expected behavior

ICONS do not fail

**Comment by mehalter** [comment]
Unable to replicate with a minimal configuration. This is happening because something like a plugin is reconfiguring the `vim.diagnostics` and it is unrelated to AstroNvim.

**Comment by mehalter** [comment]
My guess is you could have a plugin that is lazy loading on `CmdEnter` potentially and that plugin is running `vim.diagnostic.config` and it's not setting the diagnostic signs correctly. This was something that changed in v0.10 so whatever plugin it is needs to be updated.

Please do not just _ignore_ the `repro.lua` or the checklist items at the beginning of the issue. They are there to guide you to making a reproducible issue and identifying if the issue is actually AstroNvim or on the user side. If you tried the minimal `repro.lua` you would have found that the issue is not reproducible and then you would need to investigate what is necessary to reproduce it.

**Comment by ray-x** [comment]
You may need to define your own `signs` table here. `go.nvim` already using `diagnostic.config` to setup signs, which comply with neovim 0.1x requirements.

```
  diagnostic = { -- set diagnostic to false to disable diagnostic
    hdlr = false, -- hook diagnostic handler and send error to quickfix
    underline = true,
    -- virtual text setup
    virtual_text = { spacing = 0, prefix = '■' },
    update_in_insert = false,
    signs = true,  -- use a table to configure the signs texts
  },
```
