### ISSUE TITLE
Replace `neodev.nvim` with `lazydev.nvim`

### ISSUE THREAD

**Issue by Bahnasawy** [AstroNvim/AstroNvim#2618]
### Describe the new feature

`neodev.nvim` is now deprecated and folke recommends replacing it with [`lazydev.nvim`](https://github.com/folke/lazydev.nvim).

**Comment by mehalter** [comment]
Thanks for opening an issue for this! It's on the roadmap for sure with the next breaking change. The biggest reason we can't do this now is because it doesn't support 0.9 fully and for now the soft deprecation of neodev isn't going to keep it from working. Lazydev is in AstroCommunity if you want to use it early :)

**Comment by mehalter** [comment]
There are definitely also some very unfortunate limitations when it comes to it being unable to get types without explicit requires and things. We have workarounds in AstroCommunity for our core AstroNvim plugins but there may be lots of errors if you use other plugin types in your code without explicitly requiring
