### ISSUE TITLE
Filter LSPs and formatters with UI

### ISSUE THREAD

**Issue by alr86** [AstroNvim/AstroNvim#2675]
### Describe the new feature

Able users can filter LSPs and formatters based on file type with UI selectors,
I want to code it and just send RP request, but I can't filter formatters for myself :)

**Comment by mehalter** [comment]
Thanks so much for the recommendation! This is a very interesting idea.

Given the technical requirements of supporting arbitrary configurations which may use a plethora of different formatting tools in use throughout the AstroNvim community:

- language servers where each one could potentially provide formatting
- none-ls/null-ls which is a single language server that provides many formatters
- conform.nvim which handles formatting itself, separately from the LSP
- guard.nvim which handles formatting itself, separately from the LSP

This is very much out of the scope of what I would be interested in adding to core AstroNvim mainly because it would only serve a small subset of the users depending on how it's implemented. If you want to dive into this and open a PR with a recommendation, I will happily review it and let you know but I can't see a very simple implementation that is generalizable enough to be a good fit for core AstroNvim.

This seems like something that would be best implemented as it's own plugin which could then be applied to any neovim configuration and you could then have a single space to architect how it would work, integrations to include, etc. Then you would be able to add that plugin into AstroCommunity and configure it for other users if they want to add it.

For now, I'm going to close this as unplanned just purely based on the lack of generalizability in a nice way, but like I said am open to being convinced otherwise through PRs.
