### ISSUE TITLE
vimspector worked just once

### ISSUE THREAD

**Issue by crescentBLADE** [AstroNvim/AstroNvim#314]
I added the vimspector plugin yesterday and it worked for me。 

  {"puremourning/vimspector",
        config = function()
          vim.g.vimspector_enable_mappings = 'HUMAN' 
          end
      }
      
  Today the vimspector plugin is no longer in effect, but the packer manager can find him
  
![image](https://user-images.githubusercontent.com/26018987/163945050-f31a9607-d6f5-432f-8882-6c4dd76082bb.png)

**Comment by mehalter** [comment]
I'm not sure why  that would be happening since I haven't used `vimspector` before, but if it shows up  as in Packer then it definitely should be loaded. I would  open up an issue on the plugin repository and see if anyone can help you out there. If you figure out what was going on, please feel free to comment back on this issue just in case anyone else  runs into a similar problem !

**Comment by crescentBLADE** [comment]
Modify the init.lua under the User file, enable VIMSPECOTR in the default plugin
![1650513151(1)](https://user-images.githubusercontent.com/26018987/164368692-9f7af2db-1d21-4e74-b181-3c53dcaa9423.png)
