### ISSUE TITLE
Adding new plugin.

### ISSUE THREAD

**Issue by Rid1-fz-06** [AstroNvim/AstroNvim#370]
Can you please add [nvim-dap](https://github.com/mfussenegger/nvim-dap) in this configuration? It will be great and helpful (as it is quite hard to manage).

**Comment by mehalter** [comment]
nvim-dap is currently under extremely heavy development and is currently in a pretty heavy beta state with a regularly changing API. For this reason for now we aren't putting it in AstroNvim yet for stability. Also as of right now setting up DAP is very user specific and there's not much we would be able to set up ourselves outside of installing the plugin and setting nup key bindings because the adapter setup is pretty user specific.

If you want to see some examples of user configurations that do use dap you can check out the black belt configs section in the Documentation for some reference since I believe all 3 that are listed there set up DAP for different languages: https://astronvim.github.io/recipes/black_belt

**Comment by jayp0521** [comment]
@mehalter, thoughts on adding this? Would an `auto_setup` option in mason-nvim-dap make it easier to onboard? I haven't seen any breaking changes in `nvim-dap` in awhile.

**Comment by mehalter** [comment]
@jayp0521 I've been following it quite closely. The new mason dap plugin is definitely steps in the correct direction. I am waiting a bit longer to see things start really coming together and to figure out how we want to build this into AstroNvim. Maybe when Neovim 0.9 comes out in the next 3-4 months. I really don't want to rush this integration because it can add a lot of headache if things are not done carefully

**Comment by mehalter** [comment]
Hopefully that gives some insight into the path forward to getting debugging added into AstroNvim. Sorry it probably won't be super quickly/soon

**Comment by mehalter** [comment]
@jayp0521 how automated could we make the DAP setup with `mason-nvim-dap`? I like how we can set up the handlers which is a great step towards automating setup after installation. Is there a plan in `mason-nvim-dap` to provide default register code for `dap`? If we include dap set up in AstroNvim I would like it to be as seamless as we have made `null-ls` and `lspconfig`. Where it automatically configures language servers and null-ls sources. Even without adding any user configuration at all you can install these things from Mason and use them in some form. Of course this won't meet everyone's needs so we provide a way to manually configure them, but is good for 95% of use cases. I would like a similar setup for AstroNvim. But I'm not sure how we can get that with the current state of dap given how verbose the configuration is. It's not as simple nas "X.setup()".

**Comment by jayp0521** [comment]
> @jayp0521 how automated could we make the DAP setup with `mason-nvim-dap`? I like how we can set up the handlers which is a great step towards automating setup after installation. Is there a plan in `mason-nvim-dap` to provide default register code for `dap`? If we include dap set up in AstroNvim I would like it to be as seamless as we have made `null-ls` and `lspconfig`. Where it automatically configures language servers and null-ls sources. Even without adding any user configuration at all you can install these things from Mason and use them in some form. Of course this won't meet everyone's needs so we provide a way to manually configure them, but is good for 95% of use cases. I would like a similar setup for AstroNvim. But I'm not sure how we can get that with the current state of dap given how verbose the configuration is. It's not as simple nas "X.setup()".

yes, the goal of this [branch](https://github.com/jayp0521/mason-nvim-dap.nvim/tree/autoSetup) is to remove the need to configure dap at all. just pass in what you want in `ensure_installed` and set `auto_setup = true`. This should configure dap based on their [installation wiki](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation)

**Comment by mehalter** [comment]
That's awesome news @jayp0521 ! So glad to see this. I will take a look and see if there's anywhere I can help out. Another feature that would be nice is to be able to indicate auto setup and then also be able to specify debuggers to skip the setup for just in case for example I was to use the auto setup for most languages but then maybe I use a language specific plugin for one of them that I want to skip the setup for and let the plugin set it up :)

**Comment by jayp0521** [comment]
https://github.com/jayp0521/mason-nvim-dap.nvim/tree/autoSetup

this is basically done. `disable` specific plugin feature is missing, but passing your own overrides should work. https://github.com/jayp0521/mason-nvim-dap.nvim/blob/autoSetup/lua/mason-nvim-dap/mappings/adapters.lua#L55

I just need to add a few more configs for newly added adapters like `elixir`.

`automatic_setup = true`

```
automatic_setup = {
  adapters = {
     delve = {
         // your own override
     },
  },
  configurations = {
     go = {
     },
  },
}
```

**Comment by mehalter** [comment]
Awesome I can try testing this. Also I'm not sure if overriding it will be enough since plugins may do the configuration. It might be a good idea to add a way to skip certain setups if a plugin is handling the configuration of dap
