### ISSUE TITLE
How to get filename in lualine ?

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/AstroNvim#371]
WIth the usage of the global status bar, it has become harder to know which filename is open in which window/buffer. 

It would be good if you can suggest how to include the relative path of the current filename (with extension) in lualine, so that at least we can know which file is being edited when the cursor moves there.

**Comment by mehalter** [comment]
The easiest way to add the `filename` is with the `lualine` configuration in the `user/init.lua` file. A simple example would be this:

```lua
return {
  plugins = {
    lualine = function(config)
      table.insert(config.sections.lualine_c, 1, "filename")
      return config
    end,
  },
}
```

This adds the filename to the beginning of section C in lualine. This does use the `function` override format instead of the table to give more control over the overriding. This is described in the documentation: https://astronvim.github.io/configuration/override_formats#override-function

**Comment by mehalter** [comment]
You can also disable the global statusbar if you don't like it or find it hard to tell what file you are on:

https://astronvim.github.io/recipes/globalstatus

**Comment by krishnakumarg1984** [comment]
> ```lua
>     lualine = function(config)
>       table.insert(config.sections.lualine_c, 1, "filename")
>       return config
>     end,
> ```

Thank you for this. This works. 

Now, how do we suppress it for non-file buffers such as Aerial, NeoTree, etc. Currently, this shows up as `[No Name]` in my status line when the cursor is on one of these non-file buffers.
