### ISSUE TITLE
<C-w> halts after fresh install astronvim

### ISSUE THREAD

**Issue by MrPeterLee** [AstroNvim/AstroNvim#424]
Hi, I'm running into a strange issue which seems to be related to the which-key plugin. After a fresh installation (`lua/user` folder removed), hitting "`<C-w>`" multiple times will halt the nvim. Reading the log shows that the process is busy switching between the folder of which-key and the project folder. Not sure if anyone else experiences the same.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/10173354/166408276-f2cd439e-faff-4aa1-83f3-37b4f6182b2c.png">

**Comment by mehalter** [comment]
Hm, could you describe this a little more? `<c-w><c-w>` should switch between 2 open viewports (i.e. splits). I have tested on my personal configuration as well as a fresh installation and I can't get AstroNvim to hang on  multiple presses of `<c-w>`

**Comment by MrPeterLee** [comment]
Hi mehalter, thanks for a quick response. I've made a screencast on how to reproduce this issue from fresh installation (pls see [here](https://youtu.be/_xDxTaApLcs)). 

I'm relatively new to the neovim lua world (a few years of experience in vim), I'd appreciate if you could share some thoughts on the typical process to debug such glitches.

**Comment by mehalter** [comment]
Interesting. I noticed you are using Neovim nightly. Could you try to see if this bug is still present in nvim 0.7. There shouldn't be any breaking changes since the new nightly, but I should let you know that we don't currently keep up to date with the unstable nvim. I can't reproduce this on my end. The `chdir` to `which-key` is part of how plugins are activated and loaded so that shouldn't be part of the issue. That is expected behavior as plugins jump in and do their stuff. In this case though running `<c-w><c-w>` definitely shouldn't hang, but it also shouldn't do anything. If you have 2 splits open and do `<c-w><c-w>` do you get the intended behavior where it switches between the two viewports or does it also cause the editor to hang?

**Comment by MrPeterLee** [comment]
Thanks. Confirming this is not an issue in NVim 0.7. Closing the issue now.
