### ISSUE TITLE
buftype terminal keeps being set, even when editing a file in terminal mode=>E82 

### ISSUE THREAD

**Issue by AXGKl** [AstroNvim/AstroNvim#492]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [ x ] `:PackerSync`
- [ x ] `:AstroUpdate`
- [ x ] restarted AstroNvim
- [ x ] Neovim version >= 0.7.0

**Describe the bug**

In `:terminal` mode I cannot edit using neovim or even plain vim, since buftype=terminal is set, i.e. I get `E382: Cannot write, 'futype' option is set

**To Reproduce**

Open `:terminal` and try edit a file.

**Expected behavior**

Same as w/o AstroVim: Here `buftype` is empty when I open a file with it in terminal mode of an outer nvim process.

**Screenshots**

with AstroVim: https://asciinema.org/a/QHjiG0pElWPlgWweZPiQjWGbR

normal nvim:
 https://asciinema.org/a/07yaNt5Zlb3YUmKKVzN49F6hK

**Additional context**

Cannot even use plain vim in such a terminal, same error 382.

**Comment by mehalter** [comment]
This is not because of the `buftype` being set to terminal inside of the vim session. We do not do anything special with the buffers in any way. What you are running into is a binding that we have by default that doesn't make AstroNvim suitable for running vim inside of one of our terminals.

https://github.com/AstroNvim/AstroNvim/blob/ed607d58682ccb9c4deb327d1aa5f73641f01e13/lua/core/mappings.lua#L267

When you press escape you get taken out of the terminal insert mode with the default bindings. You just need to put `vim.keymap.del("t", "<esc>")` inside of your `polish` function. To remove this.

**Comment by AXGKl** [comment]
Oh man, you rock. I'd never found that - tried also `jk` but that was mapped as well :-)
