### ISSUE TITLE
Snippet matching is too fuzzy, how can I fix or remove luasnip?

### ISSUE THREAD

**Issue by axelbdt** [AstroNvim/AstroNvim#546]
Hello,
I updated AstroNvim recently (from AstroVim and neovim 0.6) and I have found that some snippets are extended in a very intrusive manner.
For example in haskell, typing ```do``` will match the ```diso``` snippet and expand to the ISO datetime.
As a quick and dirty fix, I removed ```diso``` from the friendly-snippet files, but now ```do``` will match ```data``` snippet...

Can I dial back the fuzzy snippet matching?

Another quick fix would be to disable luasnip or friendly-snippets altogether for now, but I must admit I couldn't figure it out from the docs: while it's quite clear how to add plugins, I couldn't find a way to remove or disable one.

Other than this problem, I must say I really like AstroNvim and the project brought me back from VS Code, I hope you keep up the great work.

Cheers,

**Comment by mehalter** [comment]
The fuzzy matching is provided by `cmp`. I'm not sure how to tune that matching for your needs specifically to make it less "fuzzy" that would be a good question for the `nvim-cmp` devs.

Also I will say that because of the tight coupling of how cmp is set up to play nicely with luasnip it would be quite difficult to remove it. You could disable `friendly-snippets` with the following `user/init.lua` (this does require a little bit more work than typically just removing a plugin because you need to change the lazy loading slightly):

```lua
return {
  plugins = {
    init = {
      ["rafamadriz/friendly-snippets"] = { disable = true },
      ["L3MON4D3/LuaSnip"] = { event = "InsertEnter", after = { nil } },
    },
  },
}
```

If you can't figure out how to decrease the fuzzy finding, then leaving luasnip will at least provide you a way to include your own snippets as well in your user configuration if you find a need for that in the future (https://astronvim.github.io/recipes/snippets)

**Comment by axelbdt** [comment]
This did remove the problematic snippet expansion, thanks a lot for the timely response!
