### ISSUE TITLE
How to turn lsp on automatically ?

### ISSUE THREAD

**Issue by noneback** [AstroNvim/AstroNvim#591]
The astronvim lsp server needs to be activated mannually every time I open it.  How to make it active without activating when opening it.

**Comment by mehalter** [comment]
These should start automatically out of the box. What language server are you asking about in particular? Have you made sure that the files you are opening meet the root directory requirements for the language server detecting that it should start? Also are you installing it with `nvim-lsp-installer` or is it already installed on your machine and you are just configuring the LSP?

**Comment by noneback** [comment]
`rust analyzer` and `clangd`.  My project meet the root directory requirements because it works in vscode.
 LSP is installed with `nvim-lsp-installer`, using cmd `LSPInstall`.

env: MacOS, nvim 0.7, lastest AstroNvim from main branch.

**Comment by mehalter** [comment]
Comparing it to VS Code starting automatically isn't necessarily true because they use different mechanics for automatically starting. Neovim `lspconfig` has a root file method for checking. For example, `clangd` checks for the following files by default:

```lua
local root_files = {
  '.clangd',
  '.clang-tidy',
  '.clang-format',
  'compile_commands.json',
  'compile_flags.txt',
  'configure.ac', -- AutoTools
}
```

Do you have any of these files in your project? If not, that is probably why it isn't automatically starting.


And rust checks for some type of cargo stuff. I'm not super familiar with this function so I'm not sure. I know @hunger uses rust and AstroNvim so he might have some insight on how it automatically starts:

https://github.com/neovim/nvim-lspconfig/blob/2a455c148341c4faf2dd60401397fed35d084c59/lua/lspconfig/server_configurations/rust_analyzer.lua#L17

**Comment by hunger** [comment]
The languageservers *do* work automatically, provided neovim knows what kind of file you are editing. I recommend to install [polyglot](https://github.com/sheerun/vim-polyglot), which makes neovim recognize a *lot* more kind of files (e.g. all thise related to rust!). Besides LSPs it also enables running compilers via :make as appropriate formthe language and adds parsing for compiler errors and much more. You totally want that one...

Unfortunately the astronvim devs did not agree to add this plugin, but it is a must have IMHO.

**Comment by mehalter** [comment]
Yeah `vim-polyglot` currently completely breaks the built in lua filetype stuff that is now native in Neovim `0.7` so that plugin is for sure off the table. It is also pretty dated and not super useful when adding some necessary filetypes takes a single line of config and no one is consistently opening thousands of different file types not natively supported, and would also be our slowest loading plugin by an order of like ~1000x at this point 😂

**Comment by hunger** [comment]
It is more than one line of config. It defines filetypes, compilers, parsers for compilers and regexp (== pretty useless:-) highlighting and more language features.

I am pretty sure I still use it... I'll check next time I am at my computer.

**Comment by hunger** [comment]
Anyway, maybe we could just add definitions for the more commonly used languages to asteonvim?

It is pretty static info, could be readily extracted from polyglot and would avoid more bug reports like this one... I could contribute a PR for rust at least:-)

**Comment by mehalter** [comment]
What filetypes for rust are necessary for the LSP to run? I think this is more important to get pushed upstream and not managed by AstroNvim. As there is a process for adding officially supported filetypes outside of our project.

**Comment by hunger** [comment]
This is the rust plugin that us part of polyglot: https://github.com/rust-lang/rust.vim

**Comment by abalmos** [comment]
@hunger you should consider rust-tools.nvim if you want a deeper integration with rust.

That said, rust analyzer lsp works just fine for me out of the box with Astronvim

**Comment by hunger** [comment]
I use rust-tools, but I still need the basic rust plugin, too. I get it via polyglot, but you can of course also get it separately.

**Comment by mehalter** [comment]
@arturgoms it looks like this is trying to access what seems to be a LunarVim thing. Is this coming from a plugin or part of your user config? We do not provide anything related to LunarVim or `lvim`. Do you have any rust specific plugins that could be trying this or potentially old files somewhere on your system?

**Comment by backwardspy** [comment]
i was running into this issue with `rust-analyzer` not starting until i entered insert mode, and while trying to figure out what's going on i noticed a quirk.

if i run `nvim`, and then open `src/main.rs`, rust-analyzer starts up and attaches to the buffer immediately.
if i run `nvim src/main.rs`, then rust-analyzer does not start up until i go into insert mode.

the output of `LspInfo` looks the same in both cases, it correctly identifies the root directory and so on, but in the second case it is listed under "other clients that match the filetype: rust." i can recreate this behaviour reliably on a fresh install of astronvim.

perhaps this is just how LSP works in neovim, but as i didn't realise this until just now i am putting this here in the hopes it'll help someone else who is struggling with the same issue as i was.

**Comment by mehalter** [comment]
@backwardspy do you get this on all LSP or just `rust-analyzer`?

**Comment by backwardspy** [comment]
> @backwardspy do you get this on all LSP or just `rust-analyzer`?

just tried a few, i can confirm this behaviour happens for me on a fresh astronvim for `pyright`, `gopls`, and `rust-analyzer`. those are the only ones i have handy right now, but i'm happy to try any other language servers if it helps.

**Comment by backwardspy** [comment]
i should probably mention i'm currently on `NVIM v0.8.0-dev+506-gee6b21e84`.

**Comment by mehalter** [comment]
@backwardspy  Quite strange, I can reproduce in a clean environment (on neovim stable) but it doesn't happen with my personal config 🤔 I'll have to investigate more in the coming days.

Also are you using the current nightly or the very unstable v2.0.0 branch with neovim 0.8 support? I know that the current nightly and v1.7 stable astronvim have some incompatibility with neovim 0.8 due to breaking changes. I would definitely recommend if you are using AstroNvim that you use an officially released version.

**Comment by backwardspy** [comment]
i am using the current nightly version of astronvim. that's good to know, thanks! i'll switch to a stable neovim and see how that goes.

i can't remember why i switched to neovim 0.8, so the reason can't have been that important. :)

**Comment by mehalter** [comment]
@backwardspy #831 should fix this

**Comment by backwardspy** [comment]
that seems to have done the trick! many thanks
