### ISSUE TITLE
pyright not fully working

### ISSUE THREAD

**Issue by kraxli** [AstroNvim/AstroNvim#610]
My `pyright` runs (LinuxMint, neovim 0.7)
![pyright_running](https://user-images.githubusercontent.com/8371948/172714074-a0013900-4518-487b-914e-5ae57ab9dc7f.png)

However, it does not flag all errors / warnings. E.g.

- empty line at the end of file
- using strings instead of float in `multiply(...)`
- passing only one argument to function `multiply(...)`

![pyright](https://user-images.githubusercontent.com/8371948/172714081-23e6601a-fbde-4dd2-a040-3922b3e66d6c.png)

Do I miss sth setting by using the default?

Just in case it could be of interest, I have also attached the lsp.log.
[lsp.log](https://github.com/AstroNvim/AstroNvim/files/8864975/lsp.log)

**Comment by mehalter** [comment]
ah this is a good question. Thanks for providing a solution @3LITA ! 

@kabinspace is there a reason that we set this in the global config? I am kinda leaning towards AstroNvim providing no default settings for language servers since it can make a pretty unpredictable experience for a user who's expecting a default experience for something that they set up themselves.

**Comment by kraxli** [comment]
Nice :-), thanks a lot @3LITA - works perfectly!
