### ISSUE TITLE
Disable built in themes?

### ISSUE THREAD

**Issue by soulllink** [AstroNvim/AstroNvim#664]
Is it possible to disable build in theme and let terminal and neovim defaults colors?

**Comment by mehalter** [comment]
You can set the `colorscheme = "default"` in your user configuration. This is the default colorscheme that comes with Neovim itself. I should warn you it is extremely lacking in highlight groups and looks pretty bad

**Comment by soulllink** [comment]
@mehalter thanks, that a big deal for me, but text colors still fit some other than default behavior, what should i change also?

**Comment by mehalter** [comment]
What do you mean @soulllink ?

**Comment by soulllink** [comment]
![nvim](https://user-images.githubusercontent.com/5329963/174448795-774bfa9d-fa97-4b23-8074-4e55d8ceee92.PNG)

**Comment by soulllink** [comment]
And thats default colors:
![nvimdef](https://user-images.githubusercontent.com/5329963/174448882-79a7b55a-d15f-4ce8-8b71-27e9019bcd33.PNG)

**Comment by mehalter** [comment]
This is coming from treesitter and other plugins that don't have highlight groups properly assigned so they use their own default behavior. To customize those colors you need to define your own highlight groups since those colors don't exist in the default theme. Stuff like treesitter, TS rainbow, etc. All plugins that are enabled by default and provide highlughts

**Comment by soulllink** [comment]
@mehalter thanks for explanation,
