### ISSUE TITLE
COQ autocomplete instead of cmp

### ISSUE THREAD

**Issue by half-potato** [AstroNvim/AstroNvim#668]
**Is your feature request related to a problem? Please describe.**
COQ is faster and better than cmp. 

**Describe the solution you'd like**
This also involves remapping the C-h key in COQ and enabling auto-start.

It's a drop in replacement. I have it in my config and it works very well.

**Comment by mehalter** [comment]
Can you provide an example from your configuration. I don't think `coq` is a true drop in replacement as there are a lot of community sources for `cmp` that I don't think are available for coq. It is also relatively new and much younger software. It is definitely on my list to watch as it develops, but for now this might not be a good idea for our base AstroNvim setup currently. Also because it's *not* a drop in replacement for `cmp` this is a very large breaking change and would at the very minimum need to be pushed to v2.0.0 or v3.0.0 of AstroNvim.

**Comment by mehalter** [comment]
Yeah the main thing is that `cmp` has a much larger community and selection of plugins and providers than `coq` at the moment and a lot of users use these extra providers which do not have replacements in `coq` as of yet. Maybe down the line when there is better support and everything
