### ISSUE TITLE
A video explain how to use lua.user

### ISSUE THREAD

**Issue by LintaoAmons** [AstroNvim/AstroNvim#700]
I saw there's a video shows about the out-of-box functions of astronvim,which helps a lot to newbies like me. But when comes to add user specific configuration, things became harder. So maybe another video dedicated to how to add user specific configuration, how `lua.user` overwrite the default configuration, explain a little about the things under hood~ Maybe show the process of writing a configuration, how to add new plugins, how to change the configuration of built-in plugin, how those setting Lua files merge into core configuration, etc. That will be much easier for new users~

**Comment by WillEhrendreich** [comment]
I agree, this has been very difficult to figure out, I'm almost there, but it was and still is a grueling process for the uninitiated/have a poor understanding of lua (this guy). 

having access to the "black belt example" of @mehalter has been great, but yet again another level of complication, another git repo, multiple levels of abstraction when it isn't exactly clear what is being set and where, just by the nature of it being what it is. it's full of good ideas, honestly. It's just unclear at the outset how to navigate the whole thing when you want to make changes, that's all. 

I really appreciate the work that's gone into this though, this is the closest I've been to be able to have nvim as my main editor, and that's nothing to sneeze at.

**Comment by kabinspace** [comment]
I can understand where this is coming from, the problem is things could change over time and the video made on a particular timeline would be irrelevant at some point due to those changes. Due to this, we are currently sticking with docs that get frequently updated addressing the changes made as we go on. We would instead focus on making docs more user-friendly, detailed, and understandable than making a video walkthrough. Any suggestions on docs would be highly beneficial for users as well as for us to follow up. Thank you.
