### ISSUE TITLE
Feat: Add support for options that use signs

### ISSUE THREAD

**Issue by Ya-suke** [AstroNvim/AstroNvim#722]
The ability to set options e.g. `formatoptions`, from the user config file without using autocommands would be nice.

Currently cannot set opt using `-=` or `+=` signs

The following functions exist in vim:
```lua
vim.opt.formatoptions:append("r")              -- +=
vim.opt.formatoptions:prepend("r")             -- ^=
vim.opt.formatoptions:remove("r")              -- -=
```

**Comment by mehalter** [comment]
You can do this in your `user/init.lua` file in the `polish()` function:

```lua
return {
  polish = function()
    vim.opt.formatoptions:append("r")
    vim.opt.formatoptions:prepend("r")
    vim.opt.formatoptions:remote("r")
  end
}
```

**Comment by letscho123** [comment]
I added `vim.opt.formatoptions:prepend("r")` to the `polish()` function, but it does not do anything.
When I write however in the terminal directly, it is working.
Any idea what could be the problem here?

**Comment by sbeyer** [comment]
I just stumbled over the same issue with some weird other things (probably related to filetype.lua from neovim 0.9.0). Since it does not work without autocmd, I use a autocmd. So what are my issues:

Without any config, I have `formatoptions=jcroql` in a cpp file.

With
```lua
 vim.api.nvim_create_autocmd({ "FileType" }, {
    callback = function()
      vim.opt.formatoptions:remove({ "o" })
    end,
  })
```
I get `formatoptions=cqrjl`. So far so good.

Now with
```lua
 vim.api.nvim_create_autocmd({ "FileType" }, {
    callback = function()
      vim.opt.formatoptions:append({ "/" })
    end,
  })
```
I get `formatoptions=qc1jr1lo`. I have no idea where the `1`s come from and why it eats up my `/`.
I played a little around with it and found out that this issue occurs even with a clean neovim, so it's probably a bug there and unrelated to astronvim.

My personal solution is now to provide a `opt.formatoptions = "cjlqr/"` in `options.lua` and remove the `o` via autocmd (because filetype.lua seems to add `o`). This looks like a workaround.
