### ISSUE TITLE
nvim build-in plugin TOhtml can't run

### ISSUE THREAD

**Issue by abliger** [AstroNvim/AstroNvim#745]
**Checklist**
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**

E492: not an editor command: TOhtml

**Comment by hacker-DOM** [comment]
Was about to open an issue when I ran into this.. What is the reason for this / is there a workaround? I'm used to printing code frequent and vim's ancient script is still the best way to print code imho :)

**Comment by mehalter** [comment]
@hacker-DOM you will want to remove the option we are setting to disable this plugin from loading:

```lua
return {
  options = function(config)
    config.g.loaded_2html_plugin = nil

    return config
  end,
}
``` 

Because we are removing this table entry and setting it to `nil` you will need to use the function override notation rather than the table override format. This is described here: https://astronvim.github.io/Configuration/override_formats#override-function

**Comment by hacker-DOM** [comment]
@flah00 Also I believe you can just source it manually (find its path).
