### ISSUE TITLE
[Docs]: API section on documentation

### ISSUE THREAD

**Issue by Johnsiras** [AstroNvim/AstroNvim#756]
**Is your feature request related to a problem? Please describe.**
So i'm starting to contribute to this project, and i just discovered about the **astronvim** global type and there's some functions in there that i don't understand like the `user_plugin_opts()` like what it's `module`, `default`, `extend`, `prefix`?

**Describe the solution you'd like**
Maybe you should make a new section for the `astronvim` api to understand the concept of the functions

**Comment by mehalter** [comment]
@Johnsiras @osamuaoki I just pushed a commit to #844 with doc strings for all the internal API and helper functions. If either of you get a chance could you take a look and see what you think?

**Comment by osamuaoki** [comment]
Hi,

> -----Original Message-----
> From: Micah Halter ***@***.***>
...
> @Johnsiras @osamuaoki I just pushed a commit to #844 with doc strings for all the
> internal API and helper functions. If either of you get a chance could you take a
> look and see what you think

I suppose you are talking about commit to v2 branch.

The changes look good to me (nightly pages).

If I may suggest more improvements, I think it is good idea to synchronize 
 * example in documentation https://github.com/AstroNvim/astronvim.github.io "Basic
Configuration" and,
 * `lua/user_example/init.lua` in https://github.com/AstroNvim/AstroNvim


To achieve this, I think both AstroNvim/astronvim.github.io and AstroNvim/AstroNvim
need to be modified in sync.

= AstroNvim/AstroNvim:

== IDEA #1: (higher priority)

Update its `lua/user_example/init.lua` to include section to set dashboard header
with `header = { ...` as seen in the documentation "Basic Configuration" section.
(while keeping updated contents around mapping and which-key for main.  For v2, you
need to keep UI initializer example, too)

If other features are missing, update them too.  (main? v2? -- which branch?)

== IDEA #2: (next priority)
Add a new set of split configuration examples in `lua/user_split_example/`.

= AstroNvim/astronvim.github.io:

mapping and which-key related changes in AstroNvim/AstroNvim are not reflected yet so
the followings contain old data.

 * Basic Configuration
 * Override Formats

In order to avoid this document skew problem, it may be a good idea to make this file
inclusion as a scripted process.  If we have both consolidated and split examples in
AstroNvim/AstroNvim repo, this may be much easier.  (I don't know how to do this on
docusaurus.  Many other static page builders I know do this all the time.)

Example around "cmp" and "autopairs" may need special attention for v2.

Regards,

Osamu

**Comment by mehalter** [comment]
Thanks for the feedback @osamuaoki ! also I'm not sure if you looked at the correct branch since it also has the rewrite for `user_example/init.lua` as well. I am also planning on syncing up AstroNvim.github.io with this change as it gets made and merged :)

**Comment by osamuaoki** [comment]
I looked at main and v2 of AstroNvim/AstroNvim for lua/user_example/init.lua.

I don't see   `header = { ...` in there.  I wonder why?  That is the concern for current AstroNvim/AstroNvim.

The rest of the comments are AstroNvim/astronvim.github.io  I checked out v2 branch and used "yarn start" to checked the content.

**Comment by mehalter** [comment]
@osamuaoki check out the PR that I linked in my previous comment (#844). These changes are on branch `user_example_rewrite`

**Comment by mehalter** [comment]
The documentation for the AstroNvim API can be found here:

https://astronvim.github.io/AstroNvim/

I am going to add a link to the usage documentation as I merge in an update with the new `user_example/init.lua`

**Comment by mehalter** [comment]
@osamuaoki I have also merged the change to the documentation website with the new `user_example` in the Basic Configuration page as well as a sidebar link to the Core Lua API Documentation: https://astronvim.github.io/nightly

**Comment by osamuaoki** [comment]
I can see them !  Keeping mapping in original place is better for stable release.  Great!
