### ISSUE TITLE
tab key doesn't indent, but move to another line

### ISSUE THREAD

**Issue by madyardwn** [AstroNvim/AstroNvim#782]
Tab is work for indentation, but when i write some line of code the indentation with tab not work, but move the cursor to another line. is astrovim configuration have another key for indentation? what should i do/best way for me to indent in astrovim config?

**Comment by mehalter** [comment]
This is probably because of the tab autocomplete that AstroNvimmm uses. I dislike this as well and prefer to only use `tab` for navigating through snippets if I am in a snippet or normal tab functionality. Here is an example `user/init.lua` file that changes the `<tab>` functionality to maybe behave closer to what you want (notice, this does disable the tab completion):

```lua
return {
  plugins = {
    cmp = function(config)
      local cmp = require "cmp"
      local luasnip = require "luasnip"
      config.mapping["<Tab>"] = cmp.mapping(function(fallback)
        if luasnip.expandable() then
          luasnip.expand()
        elseif luasnip.expand_or_jumpable() then
          luasnip.expand_or_jump()
        else
          fallback()
        end
      end, { "i", "s" })
      config.mapping["<S-Tab>"] = cmp.mapping(function(fallback)
        if luasnip.jumpable(-1) then
          luasnip.jump(-1)
        else
          fallback()
        end
      end, { "i", "s" })

      return config
    end,
  },
}
```

**Comment by madyardwn** [comment]
I became interested in AstroNvim default tab key configuration, but I don't get it. for a while I'll be using the default tabs like a common editor. Thanks, it worked fine and solve my problem.
