### ISSUE TITLE
Why am I getting a green background after a fresh install?

### ISSUE THREAD

**Issue by carlosmiei** [AstroNvim/AstroNvim#801]
Hello guys,
I just followed the instructions to install `AstroNVim` config but for some reason, I'm getting this weird color scheme, am I doing something wrong?  I have nothing else inside my `config/ `folder 

Instructions I followed:
```
git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim +PackerSync

```

![image](https://user-images.githubusercontent.com/43336371/181579905-64c941ce-d582-494f-9a45-6efbac375554.png)

**Comment by azinsharaf** [comment]
Are you using the default macos terminal? Use iterm, hyper etc.

**Comment by carlosmiei** [comment]
@azinsharaf yes I'm using it, but do you know why this is happening?

**Comment by azinsharaf** [comment]
astronvim requirement: "Terminal with true color support (for the default theme, otherwise it is dependent on the theme you are using)
Note when using default theme: For MacOS, the default terminal does not have true color support. You wil need to use [iTerm2](https://iterm2.com/) or another [terminal emulator](https://gist.github.com/XVilka/8346728#terminal-emulators) that has true color support.

**Comment by mehalter** [comment]
@carlosmiei, this is correct here that a terminal with true color support is a hard requirement for AstroNvim

@azinsharaf thank you so much for this detailed answer! :)

**Comment by carlosmiei** [comment]
@mehalter @azinsharaf thank you both 🙂
