### ISSUE TITLE
Can't load custom Feline configurations

### ISSUE THREAD

**Issue by Jarmos-san** [AstroNvim/AstroNvim#843]
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
I attempted to slightly configure [the default `feline` configurations](https://astronvim.github.io/configuration/plugin_defaults#feline) but AstroNvim throws an error instead. See screenshot below for reference:

![image](https://user-images.githubusercontent.com/31373860/183288215-d518da1c-0eb8-438e-b1db-2dc6d7446785.png)

Am I doing something wrong?

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a file named - `plugins/feline.lua`.
2. Return a table with the desired custom configurations (I copied the configurations as [suggested in the docs](https://astronvim.github.io/configuration/plugin_defaults#feline) & modified it a bit).

**Expected behaviour**
The statusbar should load properly without any errors.

**Comment by mehalter** [comment]
If you want to fully redefine and modify the `feline` config, you want to have this as your `user/plugins/feline.lua` file:

```lua
return function(config) -- config parameter is the default table
  local C = require "default_theme.colors"
  local hl = require("core.status").hl
  local provider = require("core.status").provider
  local conditional = require("core.status").conditional

  return {
    disable = { filetypes = { "^NvimTree$", "^neo%-tree$", "^dashboard$", "^Outline$", "^aerial$" } },
    theme = hl.group("StatusLine", { fg = C.fg, bg = C.bg_1 }),
    components = {
      active = {
        {
          { provider = provider.spacer(), hl = hl.mode() },
          { provider = provider.spacer(2) },
          { provider = "git_branch", hl = hl.fg("Conditional", { fg = C.purple_1, style = "bold" }), icon = " " },
          { provider = provider.spacer(3), enabled = conditional.git_available },
          {
            provider = { name = "file_type", opts = { filetype_icon = true, case = "lowercase" } },
            enabled = conditional.has_filetype,
          },
          { provider = provider.spacer(2), enabled = conditional.has_filetype },
          { provider = "git_diff_added", hl = hl.fg("GitSignsAdd", { fg = C.green }), icon = "  " },
          { provider = "git_diff_changed", hl = hl.fg("GitSignsChange", { fg = C.orange_1 }), icon = " 柳" },
          { provider = "git_diff_removed", hl = hl.fg("GitSignsDelete", { fg = C.red_1 }), icon = "  " },
          { provider = provider.spacer(2), enabled = conditional.git_changed },
          { provider = "diagnostic_errors", hl = hl.fg("DiagnosticError", { fg = C.red_1 }), icon = "  " },
          { provider = "diagnostic_warnings", hl = hl.fg("DiagnosticWarn", { fg = C.orange_1 }), icon = "  " },
          { provider = "diagnostic_info", hl = hl.fg("DiagnosticInfo", { fg = C.white_2 }), icon = "  " },
          { provider = "diagnostic_hints", hl = hl.fg("DiagnosticHint", { fg = C.yellow_1 }), icon = "  " },
        },
        {
          { provider = provider.lsp_progress, enabled = conditional.bar_width() },
          {
            provider = provider.lsp_client_names(true),
            short_provider = provider.lsp_client_names(),
            enabled = conditional.bar_width(),
            icon = "   ",
          },
          { provider = provider.spacer(2), enabled = conditional.bar_width() },
          {
            provider = provider.treesitter_status,
            enabled = conditional.bar_width(),
            hl = hl.fg("GitSignsAdd", { fg = C.green }),
          },
          { provider = provider.spacer(2) },
          { provider = "position" },
          { provider = provider.spacer(2) },
          { provider = "line_percentage" },
          { provider = provider.spacer() },
          { provider = "scroll_bar", hl = hl.fg("TypeDef", { fg = C.yellow }) },
          { provider = provider.spacer(2) },
          { provider = provider.spacer(), hl = hl.mode() },
        },
      },
    },
  }
end
```

Notice that there are some local variables that need to be defined and because of how the table overriding works you need to use the `function(config)...end` notations because the table extension function doesn't correctly handle modifying list style tables like the feline configuration. But this will get it into your `user/` configuration folder with full ability to override the default config.

Here is the documentation on this override format: https://astronvim.github.io/configuration/override_formats#override-function

**Comment by Jarmos-san** [comment]
I didn't know about wrapping the configurations inside the "override" function, so thanks for the heads up! Regardless, it still looks unnecessarily complicated, so can we expect things to change for the better when #715 brings [heirline.nvim](https://github.com/rebelot/heirline.nvim) to the scene?

**Comment by mehalter** [comment]
It will not because the API for configuring Heirline still heavily relies on list like tables rather than dictionary like tables. So it won't play nicely with the built in extending functions. There are ways you could simplify this, could you share your entire `feline.lua` file and I can take a look? Or just a description of what changes you are making? The code I sent is the "easiest way" but does redefine our feline configuration where you only really need to define the differences/changes you want to make to the parameter passed to the override function.

**Comment by Jarmos-san** [comment]
I've not got far ahead with configuring `feline.lua` yet because my Lua skills are a bit crappy. I was hoping to copy the suggested configurations from the documentations & make incremental changes thereafter. But I guess, I'll stick with the default statusbar customisation AstroNvim provides for awhile since v2.x is knocking on the door anyway.
