### ISSUE TITLE
How can I change the default red color?

### ISSUE THREAD

**Issue by JosePonceBetancur** [AstroNvim/AstroNvim#847]
When I type text that is not recognized as a reserved word it appears in red. I know it is designed that way, but personally I find it annoying. It is common to relate the red color with errors, I would like it to be in **white** **color**.

![image](https://user-images.githubusercontent.com/106411515/183316086-4c02356a-45a6-48a6-9ab6-479cf1c298b6.png)

How can I change it?

**Comment by mehalter** [comment]
I'm not sure if I follow. The screenshot you sent shows text in red but it is a syntax error which is what the red represents. Are there cases where it is red but is not invalid syntax and not an error in your code?

**Comment by kabinspace** [comment]
@JosePonceBetancur You can get white color for nonreserved words but do note that it's directly linked with the highlighting group of variable, so it would also make your variables look white which might look odd, apparently, there's no particular highlight for nonreserved words so that would be your only solution. You could add this to your `user/init.lua` file if you want it regardless of white variables.
```lua
      highlights.TSVariable = { fg = C.fg }
```
You can add this line somewhere inside [this](https://github.com/AstroNvim/AstroNvim/blob/ccabeb0176bea8371cc7fab1a0b7c359004e4814/lua/user_example/init.lua#L39) function.
