### ISSUE TITLE
Can't get format on save to work!

### ISSUE THREAD

**Issue by OberusPing** [AstroNvim/AstroNvim#879]
I've installed ESLint and Prettier, and I just can't get format on save to work for the life of me. I'm a new Astronvim user (and new to vim in general), but I've been trying to fix this for a while. I'm on a fresh install of Astronvim, other than the added packages. 

When I run the command manually with

`:lua vim.lsp.buf.formatting_sync()`

Then that formats the document properly. But saving it doesnt.

Do I need to make any changes to an init.lua? Any help would be appreciated.

**Comment by mehalter** [comment]
@OberusPing can you share your `user/init.lua` file?

**Comment by OberusPing** [comment]
So it wouldn't allow me to upload a .lua file (not sure if I just did something wrong there) but I copied it into a txt file. This is just a copy of the user_example init file, but I also tried several other variations. Just to make sure, it should be formatting when I type in the :w command into nvim right?

[init.txt](https://github.com/AstroNvim/AstroNvim/files/9313107/init.txt)

**Comment by mehalter** [comment]
@OberusPing have you copied the file to a new `user/` folder as described in the docs? Or is this just in the `user_example` folder?

**Comment by OberusPing** [comment]
Yep, it's in a new user/ folder!

**Comment by ledo01** [comment]
@OberusPing, here's the autocmd I have setup in my config to format on save

```lua
  vim.api.nvim_create_augroup("FormatAutogroup", { clear = true })
  vim.api.nvim_create_autocmd("BufWritePost", {
    desc = "Format on save",
    group = "FormatAutogroup",
    command = "FormatWrite",
  })
```
You can either put this in the  `polish` section of `init.lua` or in its own `polish.lua` file.
I use [formatter.nvim](https://github.com/mhartington/formatter.nvim), but replace the command with whatever you use.

Hope that helps!

**Comment by mehalter** [comment]
@ledo01 you can also do this which will save you some computation technically because it won't require writing the file twice every time you save:

```lua
  vim.api.nvim_create_augroup("FormatAutogroup", { clear = true })
  vim.api.nvim_create_autocmd("BufWritePre", {
    desc = "Format on save",
    group = "FormatAutogroup",
    command = "Format",
  })
```

@OberusPing I just tested your config in a fresh AstroNvim install. Just copied that file to a `user/` folder and upon opening it automatically installed LSP and formatters and stuff like `prettier`. I opened a test javascript file and added the contents:

```js
var x = {
  "hello": "hi"
}
```

and did `:w` to save and it immediately autoformatted it to:

```js
var x = {
  hello: "hi",
};
```

So it appears that your auto formatting is working correctly at least in the file that you have sent on this issue!
