### ISSUE TITLE
UpdateRemotePlugins not available

### ISSUE THREAD

**Issue by sutheim** [AstroNvim/AstroNvim#911]
### Question

Hey so I'm a novice vimmer so I might not understand how this is supposed to function so I'm just opening a question.
What I noticed is that if I do a fresh install of latest nvim stable and then I install Astrovim latest according to the install guide, :UpdateRemotePlugins will no longer be available, saying it is "not an editor command".
I'm on Windows 10.

to regain this functionality I had to remove the if statement at the top of nvim/runtime/plugin/rplugin.vim
```
if exists('g:loaded_remote_plugins')
  finish
endif
```

Which obviously feels hacky so am I misunderstanding something here?

**Comment by mehalter** [comment]
You are correct that this is not going to work. We disable a lot of internal and default plugins that ship with Neovim such as remote plugins and Netrw. This saves on start up time and more users don't necessarily use these plugins. You can re-enable these plugins in your `user/init.lua` file if you want. Here is an exmple `user/init.lua` configuration file:

```lua
return {
  options = function(local_vim)
    local_vim.g.loaded_remote_plugins = nil

    return local_vim
  end
}
```

**Comment by sutheim** [comment]
Thanks! Figured it was a memo I had missed!

**Comment by ywpkwon** [comment]
I tried to add
```lua
local config = {
  ...
  options = {
    opt = { ... },
    g = {
      mapleader = " ", -- sets vim.g.mapleader
      autoformat_enabled = true, -- enable or disable auto formatting at start (lsp.formatting.format_on_save must be enabled)
      ...
      loaded_remote_plugins = true,
    }
  }
}
```
- Is this different than the above solution? (I'm a lua newbie)
- Should the value be `nil` to use the command?

I tried `true` or `nil`, but still `:updateRemotePlugins` gives me `Not an editor command`. What I am I missing here?

**Comment by mehalter** [comment]
@ywpkwon yeah, you will need to set the value to `nil`. This is a very legacy `vim` feature that was before there was an idea of `boolean` values in vimscript. So to check if something was "on" or "off" they check if the value is set or not set. No matter what value you set to `loaded_remote_plugins` it will be considered "loaded" and will get skipped. That is the reason it needs to be `nil`. Because of how `lua` works you cannot do `nil` here with the table override format. You will need to use the function override format as described (https://astronvim.github.io/Configuration/override_formats) in the documentation as well as the comment above with the solution to this question.

You need to use the function override format to prevent the variable from ever being set.

**Comment by mehalter** [comment]
I would recommend checking out the code snippet that I sent in #1170 as it resolves you issue :)
