### ISSUE TITLE
Automaticly close the "Go to definition" buffer?

### ISSUE THREAD

**Issue by Stianhn** [AstroNvim/AstroNvim#919]
### Question

Hi there,

When I chose to go to definition and there are mulitple options it opens a small buffer at the bottom of the screen where I can choose which one I want to open, but it stays open after I have chosen the one I want to go to. Is it possible to have this buffer closed automaticly after I have selected where I want to go?

**Comment by mehalter** [comment]
This is default behavior of the Neovim and I'm not sure the best way to solve this in a general case as the LSP go to definition uses the quickfix menu. You can check out this stack overflow answer that I found that gives an autocommand to automatically close all quickfix menus after selection. I'm not sure if that's good behavior because it will affect all quick fix windows and not just "go to definition": https://stackoverflow.com/questions/21321357/how-can-i-cause-the-quickfix-window-to-close-after-i-select-an-item-in-it
