### ISSUE TITLE
documentation: setup user config, step 4

### ISSUE THREAD

**Issue by azinsharaf** [AstroNvim/AstroNvim#966]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

1.9.2

### Neovim version (>= 0.7)

v0.7.2

### Operating system/version

WSL (Ubuntu 22.04)

### Describe the bug

in the help document (https://astronvim.github.io/Configuration/manage_user_config) the line that copies `init.lua` file would copy the `example_user` folder into `user` folder. I think it is not correct. 

 "Copy the example init.lua file provided with AstroNvim to your user directory:"
`cp -r ~/.config/nvim/lua/user_example/ ~/.config/nvim/lua/user/`

and we end up with these subfolders:
```
tree /home/azin/.config/nvim/lua/user
/home/azin/.config/nvim/lua/user
├── README.md
└── user_example
    └── init.lua

1 directory, 2 files
```

### Steps to Reproduce

see above

### Expected behavior

I think we just need to copy the file not the `example_user` folder.

**Comment by mehalter** [comment]
@azinsharaf it is very important the trailing slashes after the 2 directories as shown in the documentation. I have just fully tested this and it works appropriately. I'm guessing when you did the command you were missing a trailing slash and did something like this `cp -r ~/.config/nvim/lua/user_example ~/.config/nvim/lua/user/` instead of what is shown in the documentation.
