### ISSUE TITLE
Overriding plugin config

### ISSUE THREAD

**Issue by seancallanan** [AstroNvim/AstroNvim#970]
### Question

I'm trying to copy a customization from LunarVim it changes the defaults for the telescope plugin to remove the preview for buffers so I added this to user/init.lua

```
local config = {
    telescope = {
        buffers = {
            previewer = false,
            initial_mode = "normal",
        },
    },
...

```

I then run :PackerSync and :AstroUpdate but when I restart I still see the preview pane if is run :Telescope buffers

p.s. I love what you have produced here and thank you

**Comment by mehalter** [comment]
This is overriding the `setup` of Telescope, so this should go in the `plugins` table. Each key in the `plugins` table such as `plugins.telescope` will override the set up of the plugin `require("telescope").setup({ ... })`

```lua
local config = {
  plugins = {
    telescope = {
        buffers = {
            previewer = false,
            initial_mode = "normal",
        },
    },
  },
...
```

**Comment by seancallanan** [comment]
Thanks for your reply.  I moved it into the plugins table as you suggested and it still is not having any affect.  Is there a way to debug if it is getting picked up?

**Comment by mehalter** [comment]
Oh wait I see, I think the problem is LunarVim has their own configuration API for telescope that does not align with the actual `telescope.setup({...})` call. They do a LOT of heavy lifting in the backend that abstracts away the "neovim-way" of doing things or how you would actually set it up yourself. I am honestly not sure what exactly they are doing with these options. One place you could get some guidance from is the Telescope documentation for configuration to see which of the real telescope options/configuration stuff you want to use: https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes

**Comment by seancallanan** [comment]
Thank for the help
